// excel_report_lifecycle — gcdeadtrace demo XLSX report generator with
// short-lived vs session-lifetime object lifecycle analysis.
//
// Extends the base excel_report.go by identifying which GC cycles correspond
// to "before session end" (short-lived freed) and "after session end"
// (session-lifetime freed), then producing cross-referenced per-site tables.
//
// Usage:
//   excel_report_lifecycle.exe [file1.txt file2.txt ...]
//
//   If no arguments are given, scans the current directory and output/
//   subdirectory for gcdeadtrace_*.txt / gcdeadtrace_*.log files automatically.
//   Otherwise, processes the specified files in the given order.
//   Each file becomes one sheet (named by its filename without .txt prefix).
//
// Output:
//   output/gcdeadtrace_report_lifecycle.xlsx — multi-sheet Excel workbook
//
// Build:
//   go build -o excel_report_lifecycle.exe excel_report_lifecycle.go
//
// Prerequisites:
//   - Input files generated by demo.exe with GODEBUG=gcdeadtrace=1
//   - No external Go dependencies (uses only archive/zip + encoding/xml)
package main

import (
	"archive/zip"
	"bufio"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// ── data types ─────────────────────────────────────────────────────

type SessionEntry struct {
	ID, GID                         int
	Allocs, AllocBytes              int
	Frees, FreeBytes                int
	Alive, AliveBytes               int
	Start, End                      string
}

type FreedAlive struct {
	Objs, Bytes, Sites int
}

type SiteLine struct {
	Func, Loc string
	Objs, Bytes int
	Refs       string
}

type GCBlock struct {
	GC                          int
	Sessions                    []SessionEntry
	Freed                       *FreedAlive
	Alive                       *FreedAlive
	FreedSites, AliveSites      []SiteLine
}

type ParsedData struct {
	Mode    string
	GCCycles []GCBlock
}

// ── parsing ────────────────────────────────────────────────────────

var (
	// session #1003: 3 allocs (1328 bytes), 0 freed (0 bytes), 3 alive (1328 bytes) [first: main.go:361 (gid=10), end: main.go:372]
	sessionRe = regexp.MustCompile(
		`\s*session (#\d+(?:#\d+)?):\s*(\d+) allocs \((\d+) bytes\),\s*(\d+) freed \((\d+) bytes\),\s*(\d+) alive \((\d+) bytes\)` +
			`(?:\s*\[first: (.+?) \(gid=(\d+)\)(.*?)\])?`,
	)
	endRe = regexp.MustCompile(`, end: (\S+)`)
	freedSumRe = regexp.MustCompile(`gcdeadsession:freed:\s*(\d+) session objs \((\d+) bytes\) freed from (\d+) sites`)
	aliveSumRe = regexp.MustCompile(`gcdeadsession:alive:\s*(\d+) session objs \((\d+) bytes\) still alive from (\d+) sites`)
	gcHeaderRe = regexp.MustCompile(`=== GC #(\d+) ===`)
	siteLineRe = regexp.MustCompile(`\s+(.+) \((\S+:\d+)\).*:\s*(\d+) session objs, (\d+) session bytes\s+(.*)`)
)

func parseInt(s string) int {
	n, _ := strconv.Atoi(s)
	return n
}

func parseFile(path string) *ParsedData {
	f, _ := os.Open(path)
	defer f.Close()
	base := strings.TrimSuffix(filepath.Base(path), ".log")
	base = strings.TrimSuffix(base, ".txt")
	mode := strings.TrimPrefix(base, "gcdeadtrace_demo_")
	data := &ParsedData{Mode: mode}
	scanner := bufio.NewScanner(f)
	var lines []string
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}
	i := 0
	for i < len(lines) && !gcHeaderRe.MatchString(lines[i]) {
		i++
	}
	for i < len(lines) {
		m := gcHeaderRe.FindStringSubmatch(lines[i])
		if m == nil { i++; continue }
		gcNum := parseInt(m[1])
		i++
		block := GCBlock{GC: gcNum}
		for i < len(lines) && !gcHeaderRe.MatchString(lines[i]) {
			line := lines[i]
			if sm := sessionRe.FindStringSubmatch(line); sm != nil {
				se := SessionEntry{
					ID: parseInt(strings.TrimPrefix(sm[1], "#")),
					Allocs: parseInt(sm[2]), AllocBytes: parseInt(sm[3]),
					Frees: parseInt(sm[4]), FreeBytes: parseInt(sm[5]),
					Alive: parseInt(sm[6]), AliveBytes: parseInt(sm[7]),
				}
				// Extract [first: ... (gid=N), ...] from inline continuation
				if sm[8] != "" {
					se.Start = sm[8]           // e.g. "main.go:361"
					se.GID = parseInt(sm[9])    // e.g. 18
					if em := endRe.FindStringSubmatch(sm[10]); em != nil {
						se.End = em[1]          // e.g. "main.go:372"
					}
				}
				block.Sessions = append(block.Sessions, se)
				i++; continue
			}
			if fm := freedSumRe.FindStringSubmatch(line); fm != nil {
				block.Freed = &FreedAlive{Objs: parseInt(fm[1]), Bytes: parseInt(fm[2]), Sites: parseInt(fm[3])}
				i++
				for i < len(lines) {
					sl := siteLineRe.FindStringSubmatch(lines[i])
					if sl == nil { break }
					block.FreedSites = append(block.FreedSites, SiteLine{strings.TrimSpace(sl[1]), sl[2], parseInt(sl[3]), parseInt(sl[4]), strings.TrimSpace(sl[5])})
					i++
				}
				continue
			}
			if am := aliveSumRe.FindStringSubmatch(line); am != nil {
				block.Alive = &FreedAlive{Objs: parseInt(am[1]), Bytes: parseInt(am[2]), Sites: parseInt(am[3])}
				i++
				for i < len(lines) {
					sl := siteLineRe.FindStringSubmatch(lines[i])
					if sl == nil { break }
					block.AliveSites = append(block.AliveSites, SiteLine{strings.TrimSpace(sl[1]), sl[2], parseInt(sl[3]), parseInt(sl[4]), strings.TrimSpace(sl[5])})
					i++
				}
				continue
			}
			i++
		}
		data.GCCycles = append(data.GCCycles, block)
	}
	return data
}

// ── XLSX builder ──────────────────────────────────────────────────

type xlsxSheet struct {
	name      string
	rows      [][]string
	colWidths []float64
}

const maxColWidth = 70.0

func (s *xlsxSheet) addRow(cells ...string) {
	s.rows = append(s.rows, cells)
	for i, c := range cells {
		w := float64(len(c)) * 1.05
		if w < 10 { w = 10 }
		if w > maxColWidth { w = maxColWidth }
		if w > s.colWidths[i] { s.colWidths[i] = w }
	}
}

func (s *xlsxSheet) addBlank() {
	s.rows = append(s.rows, nil)
}

func (s *xlsxSheet) addHeaderRow(cells ...string) {
	s.rows = append(s.rows, cells)
}

func escXML(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, "\"", "&quot;")
	return s
}

func colLetter(i int) string {
	return string(rune('A' + i))
}

func fmtFloat(f float64) string {
	if f == math.Trunc(f) {
		return fmt.Sprintf("%.0f", f)
	}
	return fmt.Sprintf("%.1f", f)
}

func (xb *xlsxBuilder) writeXLSX(path string) error {
	f, err := os.Create(path)
	if err != nil { return err }
	defer f.Close()

	w := zip.NewWriter(f)
	defer w.Close()

	// [Content_Types].xml
	ct := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
  <Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/>`
	for i := range xb.sheets {
		ct += fmt.Sprintf("\n  <Override PartName=\"/xl/worksheets/sheet%d.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet.xml\"/>", i+1)
	}
	ct += "\n</Types>"
	xb.writeFile(w, "[Content_Types].xml", ct)

	// _rels/.rels
	rels := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>`
	xb.writeFile(w, "_rels/.rels", rels)

	// xl/workbook.xml
	wb := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
          xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>`
	for i, s := range xb.sheets {
		wb += fmt.Sprintf("\n    <sheet name=\"%s\" sheetId=\"%d\" r:id=\"rId%d\"/>", escXML(s.name), i+1, i+3)
	}
	wb += "\n  </sheets>\n</workbook>"
	xb.writeFile(w, "xl/workbook.xml", wb)

	// xl/_rels/workbook.xml.rels
	wbRels := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>`
	for i := range xb.sheets {
		wbRels += fmt.Sprintf("\n  <Relationship Id=\"rId%d\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet%d.xml\"/>", i+3, i+1)
	}
	wbRels += "\n</Relationships>"
	xb.writeFile(w, "xl/_rels/workbook.xml.rels", wbRels)

	// xl/styles.xml — bold header font
	styles := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <fonts count="2">
    <font><sz val="11"/><name val="Consolas"/></font>
    <font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Consolas"/></font>
  </fonts>
  <fills count="3">
    <fill><patternFill patternType="none"/></fill>
    <fill><patternFill patternType="gray125"/></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FF4472C4"/></patternFill></fill>
  </fills>
  <borders count="2">
    <border><left/><right/><top/><bottom/><diagonal/></border>
    <border>
      <left style="thin"><color auto="1"/></left>
      <right style="thin"><color auto="1"/></right>
      <top style="thin"><color auto="1"/></top>
      <bottom style="thin"><color auto="1"/></bottom>
      <diagonal/>
    </border>
  </borders>
  <cellStyleXfs count="1">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0"/>
  </cellStyleXfs>
  <cellXfs count="4">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
    <xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center"/></xf>
    <xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1"/>
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyFont="1"><font><b/><sz val="12"/><name val="Consolas"/></font></xf>
  </cellXfs>
</styleSheet>`
	xb.writeFile(w, "xl/styles.xml", styles)

	// xl/sharedStrings.xml
	ss := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="0" uniqueCount="0"></sst>`
	xb.writeFile(w, "xl/sharedStrings.xml", ss)

	// xl/worksheets/sheetN.xml
	for si, sheet := range xb.sheets {
		colXml := "<cols>"
		for i, w := range sheet.colWidths {
			if w > 0 {
				colXml += fmt.Sprintf("<col min=\"%d\" max=\"%d\" width=\"%.1f\" customWidth=\"1\"/>", i+1, i+1, w)
			}
		}
		colXml += "</cols>"

		rowsXml := ""
		inSection := false
		for ri, row := range sheet.rows {
			if row == nil {
				rowsXml += fmt.Sprintf("<row r=\"%d\"></row>", ri+1)
				inSection = false
				continue
			}
			styleIdx := 0
			if !inSection {
				styleIdx = 1 // blue bold header
			} else {
				styleIdx = 2 // bordered data
			}
			if len(row) > 0 && (strings.HasPrefix(row[0], "==") || row[0] == "Mode:" || strings.HasPrefix(row[0], "Session #")) {
				styleIdx = 3 // section title
			}
			inSection = true

			rowsXml += fmt.Sprintf("<row r=\"%d\">", ri+1)
			for ci, cell := range row {
				ref := fmt.Sprintf("%s%d", colLetter(ci), ri+1)
				if cell == "" {
					rowsXml += fmt.Sprintf("<c r=\"%s\" s=\"%d\"/>", ref, styleIdx)
					continue
				}
				if n, err := strconv.Atoi(cell); err == nil {
					rowsXml += fmt.Sprintf("<c r=\"%s\" s=\"%d\"><v>%d</v></c>", ref, styleIdx, n)
				} else if f, err := strconv.ParseFloat(cell, 64); err == nil {
					rowsXml += fmt.Sprintf("<c r=\"%s\" s=\"%d\"><v>%s</v></c>", ref, styleIdx, fmtFloat(f))
				} else {
					rowsXml += fmt.Sprintf("<c r=\"%s\" t=\"inlineStr\" s=\"%d\"><is><t>%s</t></is></c>", ref, styleIdx, escXML(cell))
				}
			}
			rowsXml += "</row>"
		}

		sheetXml := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
           xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  %s
  <sheetData>%s</sheetData>
</worksheet>`, colXml, rowsXml)

		xb.writeFile(w, fmt.Sprintf("xl/worksheets/sheet%d.xml", si+1), sheetXml)
	}

	return nil
}

type xlsxBuilder struct {
	sheets []xlsxSheet
}

func (xb *xlsxBuilder) writeFile(w *zip.Writer, name, content string) {
	f, _ := w.Create(name)
	f.Write([]byte(content))
}

// ── build sheets from parsed data ─────────────────────────────────

type sessAgg struct {
	GID, FirstGC, LastGC            int
	Start, End                      string
	CumAllocs, CumAllocBytes        int
	CumFrees, CumFreeBytes          int
	MaxAlive, MaxAliveBytes         int
}

func buildOverviewSheet(allData []*ParsedData) *xlsxSheet {
	s := &xlsxSheet{name: "Overview", colWidths: make([]float64, 20)}
	s.addHeaderRow("Mode", "GC Cycles", "Sessions", "Freed Objs", "Freed Bytes", "Alive Objs", "Alive Bytes", "Avg Freed/GC", "Avg Alive/GC")
	for _, d := range allData {
		tf := 0
		tfBytes := 0
		for _, gc := range d.GCCycles {
			if gc.Freed != nil { tf += gc.Freed.Objs; tfBytes += gc.Freed.Bytes }
		}
		ta := 0
		taBytes := 0
		for i := len(d.GCCycles) - 1; i >= 0; i-- {
			if d.GCCycles[i].Alive != nil {
				ta = d.GCCycles[i].Alive.Objs
				taBytes = d.GCCycles[i].Alive.Bytes
				break
			}
		}
		sessSet := make(map[int]bool)
		for _, gc := range d.GCCycles {
			for _, se := range gc.Sessions { sessSet[se.ID] = true }
		}
		gcN := len(d.GCCycles)
		s.addRow(d.Mode, fmt.Sprint(gcN), fmt.Sprint(len(sessSet)),
			fmt.Sprint(tf), fmt.Sprintf("%d (%.2f MB)", tfBytes, float64(tfBytes)/1024/1024),
			fmt.Sprint(ta), fmt.Sprintf("%d (%.2f MB)", taBytes, float64(taBytes)/1024/1024),
			fmt.Sprintf("%.1f", float64(tf)/float64(gcN)),
			fmt.Sprintf("%.1f", float64(ta)/float64(gcN)))
	}
	return s
}

// ── Lifecycle analysis helpers ────────────────────────────────────

// LifecycleAnalysis holds the per-site breakdown for a single session's lifecycle.
type LifecycleAnalysis struct {
	SessionID int
	EndLoc    string

	// Before-end GC: short-lived freed + session-lifetime alive.
	BeforeEndGC      int
	ShortLivedFreed  []SiteLine // freed in before-end GC
	SessionLifetimeAlive []SiteLine // alive in before-end GC

	// After-end GC: session-lifetime objects freed.
	AfterEndGC          int
	SessionLifetimeFreed []SiteLine // freed in after-end GC

	// Cross-reference: alive sites that were also freed after end = session-lifetime objects.
	MatchedSites  []SiteMatch
	NotFreedSites []SiteLine // alive sites not found in after-end freed (potentially leaked)
}

type SiteMatch struct {
	Site      SiteLine
	FreedObjs int
	FreedBytes int
	AliveObjs int
	AliveBytes int
}

// analyzeLifecycle performs the GC orchestration analysis for a given session ID.
// Returns nil if no lifecycle pattern is detected for the session.
func analyzeLifecycle(gcs []GCBlock, sessionID int) *LifecycleAnalysis {
	var la LifecycleAnalysis
	la.SessionID = sessionID

	// Phase 1: Locate the "before end" GC (first GC where session appears without end marker).
	var beforeEndIdx int = -1
	var afterEndIdx int = -1

	for gi, gc := range gcs {
		for _, se := range gc.Sessions {
			if se.ID == sessionID {
				if se.End == "" && beforeEndIdx < 0 {
					beforeEndIdx = gi
				}
				if se.End != "" {
					la.EndLoc = se.End
					// After end: first GC with session end AND freed > 0.
					if afterEndIdx < 0 && se.Frees > 0 && gi != beforeEndIdx {
						afterEndIdx = gi
					}
				}
			}
		}
	}

	if beforeEndIdx < 0 {
		return nil // no lifecycle pattern detected
	}

	la.BeforeEndGC = gcs[beforeEndIdx].GC
	la.ShortLivedFreed = gcs[beforeEndIdx].FreedSites
	la.SessionLifetimeAlive = gcs[beforeEndIdx].AliveSites

	if afterEndIdx >= 0 {
		la.AfterEndGC = gcs[afterEndIdx].GC
		la.SessionLifetimeFreed = gcs[afterEndIdx].FreedSites
	}

	// Cross-reference: session-lifetime alive sites (from before-end GC) vs freed after end.
	type siteKey struct{ funcName, loc string }
	aliveByKey := make(map[siteKey]SiteLine)
	for _, site := range la.SessionLifetimeAlive {
		key := siteKey{firstFileLine(site.Func, site.Loc), site.Loc}
		aliveByKey[key] = site
	}

	freedByKey := make(map[siteKey]SiteLine)
	for _, site := range la.SessionLifetimeFreed {
		key := siteKey{firstFileLine(site.Func, site.Loc), site.Loc}
		freedByKey[key] = site
	}

	// Matched: alive site that appears in after-end freed = session-lifetime.
	for key, alive := range aliveByKey {
		if freed, ok := freedByKey[key]; ok {
			la.MatchedSites = append(la.MatchedSites, SiteMatch{
				Site:       alive,
				AliveObjs:  alive.Objs,
				AliveBytes: alive.Bytes,
				FreedObjs:  freed.Objs,
				FreedBytes: freed.Bytes,
			})
		}
	}
	sort.Slice(la.MatchedSites, func(i, j int) bool {
		return la.MatchedSites[i].AliveBytes > la.MatchedSites[j].AliveBytes
	})

	// Not freed: alive site not found in after-end freed (potentially leaked or runtime).
	for key, alive := range aliveByKey {
		if _, ok := freedByKey[key]; !ok {
			la.NotFreedSites = append(la.NotFreedSites, alive)
		}
	}
	sort.Slice(la.NotFreedSites, func(i, j int) bool {
		return la.NotFreedSites[i].Bytes > la.NotFreedSites[j].Bytes
	})

	return &la
}

// ── build mode sheet with lifecycle analysis ──────────────────────

func buildModeSheet(data *ParsedData) *xlsxSheet {
	s := &xlsxSheet{name: data.Mode, colWidths: make([]float64, 20)}
	gcs := data.GCCycles

	tf := 0
	tfBytes := 0
	for _, gc := range gcs {
		if gc.Freed != nil { tf += gc.Freed.Objs; tfBytes += gc.Freed.Bytes }
	}
	ta := 0
	taBytes := 0
	for i := len(gcs) - 1; i >= 0; i-- {
		if gcs[i].Alive != nil {
			ta = gcs[i].Alive.Objs
			taBytes = gcs[i].Alive.Bytes
			break
		}
	}
	sessSet := make(map[int]bool)
	for _, gc := range gcs {
		for _, se := range gc.Sessions { sessSet[se.ID] = true }
	}

	// siteInfo struct for site attribution aggregation.
	type sInfo struct {
		Func, Loc          string
		TotalObjs, TotalBytes int
		Refs               map[string]bool
	}

	// ── Pre-compute summary statistics for the top-of-sheet summary ──
	// Freed site totals.
	fSumObjs, fSumBytes := 0, 0
	fSumMap := make(map[string]*sInfo)
	for _, gc := range gcs {
		for _, site := range gc.FreedSites {
			key := site.Func + "|" + site.Loc
			si, ok := fSumMap[key]
			if !ok { si = &sInfo{Func: site.Func, Loc: site.Loc, Refs: make(map[string]bool)}; fSumMap[key] = si }
			si.TotalObjs += site.Objs; si.TotalBytes += site.Bytes
		}
	}
	for _, si := range fSumMap { fSumObjs += si.TotalObjs; fSumBytes += si.TotalBytes }

	// Alive site totals — use LAST GC cycle's snapshot (alive is NOT additive across cycles).
	aSumObjs, aSumBytes := 0, 0
	aSumMap := make(map[string]*sInfo)
	for i := len(gcs) - 1; i >= 0; i-- {
		if len(gcs[i].AliveSites) > 0 {
			for _, site := range gcs[i].AliveSites {
				key := site.Func + "|" + site.Loc
				if _, ok := aSumMap[key]; !ok {
					aSumMap[key] = &sInfo{Func: site.Func, Loc: site.Loc, TotalObjs: site.Objs, TotalBytes: site.Bytes, Refs: make(map[string]bool)}
					aSumObjs += site.Objs
					aSumBytes += site.Bytes
				}
			}
			break
		}
	}

	// Cross-reference by file:line for Both/Only counts.
	type sumLineAgg struct {
		FreedObjs, FreedBytes, AliveObjs, AliveBytes int
	}
	fSumByLine := make(map[string]*sumLineAgg)
	aSumByLine := make(map[string]*sumLineAgg)
	for _, si := range fSumMap {
		loc := firstFileLine(si.Func, si.Loc)
		if loc == "" { continue }
		a, ok := fSumByLine[loc]
		if !ok { a = &sumLineAgg{}; fSumByLine[loc] = a }
		a.FreedObjs += si.TotalObjs; a.FreedBytes += si.TotalBytes
	}
	for _, si := range aSumMap {
		loc := firstFileLine(si.Func, si.Loc)
		if loc == "" { continue }
		a, ok := aSumByLine[loc]
		if !ok { a = &sumLineAgg{}; aSumByLine[loc] = a }
		a.AliveObjs += si.TotalObjs; a.AliveBytes += si.TotalBytes
	}
	nBoth, nOnly := 0, 0
	tBFreedObjs, tBFreedBytes, tBAliveObjs, tBAliveBytes := 0, 0, 0, 0
	tOFreedObjs, tOFreedBytes := 0, 0
	for loc := range fSumByLine {
		if _, ok := aSumByLine[loc]; ok {
			nBoth++
			tBFreedObjs += fSumByLine[loc].FreedObjs
			tBFreedBytes += fSumByLine[loc].FreedBytes
			tBAliveObjs += aSumByLine[loc].AliveObjs
			tBAliveBytes += aSumByLine[loc].AliveBytes
		}
	}
	for loc := range fSumByLine {
		if _, ok := aSumByLine[loc]; !ok {
			nOnly++
			tOFreedObjs += fSumByLine[loc].FreedObjs
			tOFreedBytes += fSumByLine[loc].FreedBytes
		}
	}

	// Build sids for session totals (used by both summary and session detail).
	sids := make(map[int]*sessAgg)
	for _, gc := range gcs {
		for _, se := range gc.Sessions {
			sa, ok := sids[se.ID]
			if !ok {
				sa = &sessAgg{GID: se.GID, FirstGC: gc.GC, Start: se.Start}
				sids[se.ID] = sa
			}
			sa.LastGC = gc.GC
			sa.CumAllocs += se.Allocs
			sa.CumAllocBytes += se.AllocBytes
			sa.CumFrees += se.Frees
			sa.CumFreeBytes += se.FreeBytes
			if se.Alive > sa.MaxAlive { sa.MaxAlive = se.Alive; sa.MaxAliveBytes = se.AliveBytes }
			if se.End != "" { sa.End = se.End }
		}
	}
	var sorted []int
	for id := range sids { sorted = append(sorted, id) }
	sort.Ints(sorted)

	// Session totals (from sids).
	sAllocs, sAllocBytes, sFrees, sFreeBytes := 0, 0, 0, 0
	for _, id := range sorted {
		sa := sids[id]
		sAllocs += sa.CumAllocs; sAllocBytes += sa.CumAllocBytes
		sFrees += sa.CumFrees; sFreeBytes += sa.CumFreeBytes
	}
	sLastAlive, sLastAliveBytes := 0, 0
	for i := len(gcs) - 1; i >= 0; i-- {
		if gcs[i].Alive != nil {
			sLastAlive = gcs[i].Alive.Objs
			sLastAliveBytes = gcs[i].Alive.Bytes
			break
		}
	}

	// ── Write rows ──
	s.addRow("Mode:", data.Mode)
	s.addRow("GC Cycles:", fmt.Sprint(len(gcs)))
	s.addRow("Sessions:", fmt.Sprint(len(sessSet)))
	s.addRow("Total Freed:", fmt.Sprint(tf))
	s.addRow("Total Freed Bytes:", fmt.Sprintf("%d (%.2f MB)", tfBytes, float64(tfBytes)/1024/1024))
	s.addRow("Total Alive:", fmt.Sprint(ta))
	s.addRow("Total Alive Bytes:", fmt.Sprintf("%d (%.2f MB)", taBytes, float64(taBytes)/1024/1024))
	s.addBlank()

	// Summary block with section-level totals at the top of the sheet.
	s.addRow("=== Summary ===")
	s.addRow("Session Detail (alloc/freed/alive)",
		fmt.Sprintf("%d / %d / %d objs", sAllocs, sFrees, sLastAlive),
		fmt.Sprintf("%s / %s / %s",
			fmt.Sprintf("%d (%.2f MB)", sAllocBytes, float64(sAllocBytes)/1024/1024),
			fmt.Sprintf("%d (%.2f MB)", sFreeBytes, float64(sFreeBytes)/1024/1024),
			fmt.Sprintf("%d (%.2f MB)", sLastAliveBytes, float64(sLastAliveBytes)/1024/1024)),
		"", "")
	s.addRow("Freed Sites",
		fmt.Sprintf("%d lines, %d objs", len(fSumMap), fSumObjs),
		fmt.Sprintf("%d (%.2f MB)", fSumBytes, float64(fSumBytes)/1024/1024),
		"", "")
	s.addRow("Alive Sites",
		fmt.Sprintf("%d lines, %d objs", len(aSumMap), aSumObjs),
		fmt.Sprintf("%d (%.2f MB)", aSumBytes, float64(aSumBytes)/1024/1024),
		"", "")
	s.addRow("Both Freed & Alive",
		fmt.Sprintf("%d lines (%d freed, %d alive)", nBoth, tBFreedObjs, tBAliveObjs),
		fmt.Sprintf("freed %s / alive %s",
			fmt.Sprintf("%d (%.2f MB)", tBFreedBytes, float64(tBFreedBytes)/1024/1024),
			fmt.Sprintf("%d (%.2f MB)", tBAliveBytes, float64(tBAliveBytes)/1024/1024)),
		"", "")
	s.addRow("Only in Freed (fully dead)",
		fmt.Sprintf("%d lines, %d objs", nOnly, tOFreedObjs),
		fmt.Sprintf("%d (%.2f MB)", tOFreedBytes, float64(tOFreedBytes)/1024/1024),
		"", "")
	s.addBlank()

	// Per-GC Summary
	s.addHeaderRow("GC", "Sessions", "Freed Objs", "Freed Bytes", "Alive Objs", "Alive Bytes")
	for _, gc := range gcs {
		fO, fB, aO, aB := "0", "0", "0", "0"
		if gc.Freed != nil { fO = fmt.Sprint(gc.Freed.Objs); fB = fmt.Sprint(gc.Freed.Bytes) }
		if gc.Alive != nil { aO = fmt.Sprint(gc.Alive.Objs); aB = fmt.Sprint(gc.Alive.Bytes) }
		s.addRow(fmt.Sprint(gc.GC), fmt.Sprint(len(gc.Sessions)), fO, fB, aO, aB)
	}
	s.addBlank()

	// Session Detail
	s.addHeaderRow("Session", "GID", "First GC", "Last GC", "Start", "End",
		"Total Allocs", "Alloc Bytes", "Total Frees", "Free Bytes", "Max Alive", "Max Alive Bytes")
	s.addRow("Total", "", "", "", "", "",
		fmt.Sprint(sAllocs), fmt.Sprintf("%d (%.2f MB)", sAllocBytes, float64(sAllocBytes)/1024/1024),
		fmt.Sprint(sFrees), fmt.Sprintf("%d (%.2f MB)", sFreeBytes, float64(sFreeBytes)/1024/1024),
		fmt.Sprint(sLastAlive), fmt.Sprintf("%d (%.2f MB)", sLastAliveBytes, float64(sLastAliveBytes)/1024/1024))
	for _, id := range sorted {
		sa := sids[id]
		s.addRow(fmt.Sprintf("#%d", id), fmt.Sprint(sa.GID),
			fmt.Sprintf("GC#%d", sa.FirstGC), fmt.Sprintf("GC#%d", sa.LastGC),
			shortLoc(sa.Start), shortLoc(sa.End),
			fmt.Sprint(sa.CumAllocs), fmt.Sprint(sa.CumAllocBytes),
			fmt.Sprint(sa.CumFrees), fmt.Sprint(sa.CumFreeBytes),
			fmt.Sprint(sa.MaxAlive), fmt.Sprint(sa.MaxAliveBytes))
	}

	// Freed Site Attribution
	s.addBlank()
	s.addRow("=== Freed Sites ===")
	s.addHeaderRow("Allocation Site", "Alloc File:Line", "Freed Objs", "Freed Bytes", "Session Refs")
	type siteInfo struct {
		Func, Loc          string
		TotalObjs, TotalBytes int
		Refs               map[string]bool
	}
	emitSites := func(siteMap map[string]*siteInfo, title string) {
		var sites []*siteInfo
		tObjs, tBytes := 0, 0
		for _, si := range siteMap { sites = append(sites, si); tObjs += si.TotalObjs; tBytes += si.TotalBytes }
		sort.Slice(sites, func(i, j int) bool { return sites[i].TotalBytes > sites[j].TotalBytes })
		for _, si := range sites {
			var refs []string
			for r := range si.Refs { refs = append(refs, r) }
			sort.Strings(refs)
			refStr := strings.Join(refs, "; ")
			if len(refStr) > 10000 { refStr = refStr[:9997] + "..." }
			loc := firstFileLine(si.Func, si.Loc)
			s.addRow(si.Func, loc, fmt.Sprint(si.TotalObjs), fmt.Sprint(si.TotalBytes), refStr)
		}
	}
	freedMap := make(map[string]*siteInfo)
	for _, gc := range gcs {
		for _, site := range gc.FreedSites {
			key := site.Func + "|" + site.Loc
			si, ok := freedMap[key]
			if !ok { si = &siteInfo{Func: site.Func, Loc: site.Loc, Refs: make(map[string]bool)}; freedMap[key] = si }
			si.TotalObjs += site.Objs; si.TotalBytes += site.Bytes; si.Refs[site.Refs] = true
		}
	}
	emitSites(freedMap, "Freed")

	// Alive Site Attribution
	s.addBlank()
	s.addRow("=== Alive Sites ===")
	s.addHeaderRow("Allocation Site", "Alloc File:Line", "Alive Objs", "Alive Bytes", "Session Refs")
	aliveMap := make(map[string]*siteInfo)
	for i := len(gcs) - 1; i >= 0; i-- {
		if len(gcs[i].AliveSites) > 0 {
			for _, site := range gcs[i].AliveSites {
				key := site.Func + "|" + site.Loc
				if _, ok := aliveMap[key]; !ok {
					aliveMap[key] = &siteInfo{Func: site.Func, Loc: site.Loc,
						TotalObjs: site.Objs, TotalBytes: site.Bytes, Refs: make(map[string]bool)}
				}
				aliveMap[key].Refs[site.Refs] = true
			}
			break
		}
	}
	emitSites(aliveMap, "Alive")

	// Cross-reference by Alloc File:Line
	s.addBlank()
	s.addRow("=== Alloc File:Line in Both Freed & Alive ===")
	s.addHeaderRow("Alloc File:Line", "Freed Objs", "Freed Bytes", "Alive Objs", "Alive Bytes", "#Stacks", "Call Stacks")
	type lineAgg struct {
		FreedObjs, FreedBytes, AliveObjs, AliveBytes int
		Funcs                                        map[string]bool
		Types                                        map[string]bool
	}
	freedByLine := make(map[string]*lineAgg)
	aliveByLine := make(map[string]*lineAgg)
	for _, si := range freedMap {
		loc := firstFileLine(si.Func, si.Loc)
		if loc == "" { continue }
		a, ok := freedByLine[loc]
		if !ok { a = &lineAgg{Funcs: make(map[string]bool), Types: make(map[string]bool)}; freedByLine[loc] = a }
		a.FreedObjs += si.TotalObjs
		a.FreedBytes += si.TotalBytes
		a.Funcs[si.Func] = true
		for _, t := range extractTypes(si.Refs) { a.Types[t] = true }
	}
	for _, si := range aliveMap {
		loc := firstFileLine(si.Func, si.Loc)
		if loc == "" { continue }
		a, ok := aliveByLine[loc]
		if !ok { a = &lineAgg{Funcs: make(map[string]bool)}; aliveByLine[loc] = a }
		a.AliveObjs += si.TotalObjs
		a.AliveBytes += si.TotalBytes
		a.Funcs[si.Func] = true
	}
	// Both freed & alive — sorted by Freed Bytes desc
	var bothLines []string
	for loc := range freedByLine {
		if _, ok := aliveByLine[loc]; ok {
			bothLines = append(bothLines, loc)
		}
	}
	sort.Slice(bothLines, func(i, j int) bool {
		return freedByLine[bothLines[i]].FreedBytes > freedByLine[bothLines[j]].FreedBytes
	})
	for _, loc := range bothLines {
		fa := freedByLine[loc]
		aa := aliveByLine[loc]
		funcs := make([]string, 0, len(fa.Funcs))
		for f := range fa.Funcs { funcs = append(funcs, f) }
		for f := range aa.Funcs { funcs = append(funcs, f) }
		sort.Strings(funcs)
		fnStr := strings.Join(funcs, "; ")
		if len(fnStr) > 10000 { fnStr = fnStr[:9997] + "..." }
		s.addRow(loc, fmt.Sprint(fa.FreedObjs), fmt.Sprint(fa.FreedBytes),
			fmt.Sprint(aa.AliveObjs), fmt.Sprint(aa.AliveBytes),
			fmt.Sprint(len(funcs)), fnStr)
	}
	if len(bothLines) == 0 {
		s.addRow("(none)")
	}

	// Freed only — sorted by Freed Bytes desc
	s.addBlank()
	s.addRow("=== Alloc File:Line Only in Freed (fully dead) ===")
	s.addHeaderRow("Alloc File:Line", "Type", "Freed Objs", "Freed Bytes", "#Stacks", "Call Stacks")
	var onlyLines []string
	for loc := range freedByLine {
		if _, ok := aliveByLine[loc]; !ok {
			onlyLines = append(onlyLines, loc)
		}
	}
	sort.Slice(onlyLines, func(i, j int) bool {
		return freedByLine[onlyLines[i]].FreedBytes > freedByLine[onlyLines[j]].FreedBytes
	})
	if len(onlyLines) == 0 {
		s.addRow("(none)")
	} else {
		for _, loc := range onlyLines {
			fa := freedByLine[loc]
			types := make([]string, 0, len(fa.Types))
			for t := range fa.Types { types = append(types, t) }
			sort.Strings(types)
			typeStr := strings.Join(types, "; ")
			funcs := make([]string, 0, len(fa.Funcs))
			for f := range fa.Funcs { funcs = append(funcs, f) }
			sort.Strings(funcs)
			fnStr := strings.Join(funcs, "; ")
			if len(fnStr) > 10000 { fnStr = fnStr[:9997] + "..." }
			s.addRow(loc, typeStr, fmt.Sprint(fa.FreedObjs), fmt.Sprint(fa.FreedBytes),
				fmt.Sprint(len(funcs)), fnStr)
		}
	}

	// ═══════════════════════════════════════════════════════════════
	// Session Lifecycle Analysis
	// ═══════════════════════════════════════════════════════════════
	// Only applicable for sessionlifecycle mode (GC orchestration pattern).
	if strings.Contains(strings.ToLower(data.Mode), "sessionlifecycle") {
		// Analyze session 9001 (the orchestrated session).
		la := analyzeLifecycle(gcs, 9001)
		if la != nil {
			s.addBlank()
			s.addRow("=== Session Lifecycle Analysis (Session #9001) ===")
			s.addRow("Methodology: GC orchestration — forced GC before session end (short-lived freed,")
			s.addRow("session-lifetime alive), then GcDeadSessionEnd + drop refs + forced GC")
			s.addRow("(session-lifetime freed). Session-lifetime = alive in GC #1, freed in GC #2.")
			s.addBlank()

			// ── Phase 1: GC Timeline with lifecycle markers ──
			s.addRow("GC Timeline with Lifecycle Markers:")
			s.addHeaderRow("GC", "Session 9001 State", "Allocs", "Short-Lived Freed", "Session-Lifetime Alive", "Session-Lifetime Freed", "Notes")
			for _, gc := range gcs {
				var se *SessionEntry
				for i := range gc.Sessions {
					if gc.Sessions[i].ID == la.SessionID {
						se = &gc.Sessions[i]
						break
					}
				}
				if se == nil { continue }

				state := "active (no end)"
				notes := ""
				if se.End != "" {
					state = "ended"
					if gc.GC == la.AfterEndGC {
						notes = "← session-lifetime objects freed here"
					} else if se.Frees == 0 && gc.GC != la.BeforeEndGC {
						notes = "background GC, no new frees"
					}
				}
				if gc.GC == la.BeforeEndGC {
					state = "active (short-lived freed)"
					notes = "← GC #1: first forced GC"
				}

				slFreed := "—"
				slAlive := "—"
				slFreedAfter := "—"
				if gc.GC == la.BeforeEndGC {
					shortLivedTotal := 0
					shortLivedBytes := 0
					for _, site := range la.ShortLivedFreed {
						shortLivedTotal += site.Objs
						shortLivedBytes += site.Bytes
					}
					slFreed = fmt.Sprintf("%d objs (%d bytes)", shortLivedTotal, shortLivedBytes)
					aliveTotal := 0
					aliveBytes := 0
					for _, site := range la.SessionLifetimeAlive {
						aliveTotal += site.Objs
						aliveBytes += site.Bytes
					}
					slAlive = fmt.Sprintf("%d objs (%d bytes)", aliveTotal, aliveBytes)
				}
				if gc.GC == la.AfterEndGC {
					freedTotal := 0
					freedBytes := 0
					for _, site := range la.SessionLifetimeFreed {
						freedTotal += site.Objs
						freedBytes += site.Bytes
					}
					slFreedAfter = fmt.Sprintf("%d objs (%d bytes)", freedTotal, freedBytes)
				}

				s.addRow(fmt.Sprint(gc.GC), state,
					fmt.Sprint(se.Allocs), slFreed, slAlive, slFreedAfter, notes)
			}
			s.addBlank()

			// ── Phase 2: Short-lived freed per-site detail ──
			s.addRow("=== Short-Lived Object Sites (Freed During Session, Before GcDeadSessionEnd) ===")
			s.addRow(fmt.Sprintf("Freed at GC #%d — these objects were allocated and freed within the session,",
				la.BeforeEndGC))
			s.addRow("before the session ended. They are NOT session-lifetime objects.")
			s.addBlank()
			if len(la.ShortLivedFreed) > 0 {
				s.addHeaderRow("Allocation Site", "File:Line", "Freed Objs", "Freed Bytes", "Session Refs")
				for _, site := range la.ShortLivedFreed {
					loc := firstFileLine(site.Func, site.Loc)
					s.addRow(site.Func, loc, fmt.Sprint(site.Objs), fmt.Sprint(site.Bytes), site.Refs)
				}
			} else {
				s.addRow("(no short-lived freed objects detected)")
			}
			s.addBlank()

			// ── Phase 3: Session-lifetime freed per-site detail ──
			s.addRow("=== Session-Lifetime Object Sites (Freed After GcDeadSessionEnd) ===")
			s.addRow(fmt.Sprintf("Freed at GC #%d — these objects were allocated during the session,",
				la.AfterEndGC))
			s.addRow("stayed alive through the first forced GC, and were freed only after")
			s.addRow("the session ended and references were dropped. These are the objects")
			s.addRow("whose lifetime exactly matches the session duration.")
			s.addBlank()
			if len(la.SessionLifetimeFreed) > 0 {
				s.addHeaderRow("Allocation Site", "File:Line", "Freed Objs", "Freed Bytes", "Session Refs")
				freedSiteTotal := 0
				freedSiteBytes := 0
				for _, site := range la.SessionLifetimeFreed {
					loc := firstFileLine(site.Func, site.Loc)
					s.addRow(site.Func, loc, fmt.Sprint(site.Objs), fmt.Sprint(site.Bytes), site.Refs)
					freedSiteTotal += site.Objs
					freedSiteBytes += site.Bytes
				}
				s.addRow("Total", "", fmt.Sprint(freedSiteTotal), fmt.Sprint(freedSiteBytes), "")
			} else {
				s.addRow("(no session-lifetime freed objects detected)")
			}
			s.addBlank()

			// ── Phase 4: Cross-reference: alive → freed ──
			s.addRow("=== Cross-Reference: Session-Lifetime Alive (GC #1) → Freed (After End) ===")
			s.addHeaderRow("Allocation Site", "File:Line",
				"GC #1 Alive Objs", "GC #1 Alive Bytes",
				"After-End Freed Objs", "After-End Freed Bytes",
				"Matched?")
			if len(la.MatchedSites) > 0 {
				for _, m := range la.MatchedSites {
					loc := firstFileLine(m.Site.Func, m.Site.Loc)
					matched := "YES"
					if m.AliveObjs != m.FreedObjs || m.AliveBytes != m.FreedBytes {
						matched = fmt.Sprintf("PARTIAL (%d alive → %d freed)", m.AliveObjs, m.FreedObjs)
					}
					s.addRow(m.Site.Func, loc,
						fmt.Sprint(m.AliveObjs), fmt.Sprint(m.AliveBytes),
						fmt.Sprint(m.FreedObjs), fmt.Sprint(m.FreedBytes),
						matched)
				}
			}
			if len(la.NotFreedSites) > 0 {
				for _, site := range la.NotFreedSites {
					loc := firstFileLine(site.Func, site.Loc)
					s.addRow(site.Func, loc,
						fmt.Sprint(site.Objs), fmt.Sprint(site.Bytes),
						"0", "0",
						"NOT FREED (runtime/persistent)")
				}
			}
			if len(la.MatchedSites) == 0 && len(la.NotFreedSites) == 0 {
				s.addRow("(no data for cross-reference)")
			}

			// ── Phase 5: Summary ──
			s.addBlank()
			shortLivedTotal := 0
			shortLivedBytes := 0
			for _, site := range la.ShortLivedFreed { shortLivedTotal += site.Objs; shortLivedBytes += site.Bytes }
			sessLifeTotal := 0
			sessLifeBytes := 0
			for _, site := range la.SessionLifetimeFreed { sessLifeTotal += site.Objs; sessLifeBytes += site.Bytes }
			notFreedTotal := 0
			notFreedBytes := 0
			for _, site := range la.NotFreedSites { notFreedTotal += site.Objs; notFreedBytes += site.Bytes }

			s.addRow("=== Lifecycle Summary ===")
			s.addRow("Short-lived (freed before session end)", fmt.Sprintf("%d objs", shortLivedTotal), fmt.Sprintf("%d bytes", shortLivedBytes))
			s.addRow("Session-lifetime (freed after session end)", fmt.Sprintf("%d objs", sessLifeTotal), fmt.Sprintf("%d bytes", sessLifeBytes))
			s.addRow("Runtime-persistent (never freed)", fmt.Sprintf("%d objs", notFreedTotal), fmt.Sprintf("%d bytes", notFreedBytes))
			s.addBlank()
			s.addRow("Session total allocs", fmt.Sprintf("%d objs", shortLivedTotal+sessLifeTotal+notFreedTotal),
				fmt.Sprintf("%d bytes", shortLivedBytes+sessLifeBytes+notFreedBytes))
			s.addRow("(matches GC #1 session output above: allocs − frees − alive = 0)")
		}
	}

	// Reprint timeline (unchanged)
	if strings.Contains(strings.ToLower(data.Mode), "reprint") {
		s.addBlank()
		s.addRow("=== Session Timeline (Re-print Verification) ===")
		for _, id := range sorted {
			sa := sids[id]
			s.addBlank()
			s.addRow(fmt.Sprintf("Session #%d (GID=%d)", id, sa.GID))
			s.addHeaderRow("GC", "Type", "Allocs", "Frees", "Alive", "end?")
			var appGCs []int
			for _, gc := range gcs {
				for _, se := range gc.Sessions {
					if se.ID == id {
						typ := "first print"
						if se.End != "" { typ = "re-print" }
						hasEnd := "NO"
						if se.End != "" { hasEnd = "YES" }
						s.addRow(fmt.Sprint(gc.GC), typ, fmt.Sprint(se.Allocs), fmt.Sprint(se.Frees), fmt.Sprint(se.Alive), hasEnd)
						appGCs = append(appGCs, gc.GC)
					}
				}
			}
			if len(appGCs) >= 2 {
				for mid := appGCs[0] + 1; mid < appGCs[len(appGCs)-1]; mid++ {
					skipped := true
					for _, agc := range appGCs { if agc == mid { skipped = false; break } }
					if skipped {
						s.addRow(fmt.Sprint(mid), "(skipped)", "", "", "", "")
					}
				}
			}
		}
	}

	return s
}

func shortLoc(loc string) string {
	if idx := strings.Index(loc, ":"); idx >= 0 {
		base := filepath.Base(loc[:idx])
		return base + loc[idx:]
	}
	return loc
}

// firstFileLine extracts the first (file:line) from a call stack string.
// The call stack format from gcdeadtrace is:
//
//	topFunc (file1.go:123) < caller (file2.go:456) < ...
//
// Returns fallback when the stack doesn't contain a (file:line) pair.
func firstFileLine(stack, fallback string) string {
	idx := strings.Index(stack, " (")
	if idx < 0 {
		return fallback
	}
	start := idx + 2
	end := strings.Index(stack[start:], ")")
	if end < 0 {
		return fallback
	}
	return stack[start : start+end]
}

// extractTypes extracts unique @type annotations from a map of ref strings.
// Refs can contain multiple [session ...] blocks, e.g.:
//
//	"[session #3001: 1 objs, 256 bytes @uint8 (gid=18)] [session #3001: 1 objs, 256 bytes @uint8 (gid=19)]"
//
// Each block may also omit the type entirely, e.g. "[session #4002: 1 objs, 32 bytes (gid=6)]".
func extractTypes(refs map[string]bool) []string {
	seen := make(map[string]bool)
	for r := range refs {
		parts := strings.Split(r, "] [")
		for _, part := range parts {
			atIdx := strings.Index(part, "@")
			if atIdx < 0 {
				continue
			}
			rest := part[atIdx+1:]
			end := strings.IndexAny(rest, " ]")
			if end < 0 {
				end = len(rest)
			}
			t := rest[:end]
			if t != "" {
				seen[t] = true
			}
		}
	}
	var types []string
	for t := range seen { types = append(types, t) }
	sort.Strings(types)
	return types
}

// ── main ───────────────────────────────────────────────────────────

func main() {
	var inputFiles []string
	if len(os.Args) > 1 {
		inputFiles = os.Args[1:]
	} else {
		for _, dir := range []string{".", "output"} {
			for _, ext := range []string{"gcdeadtrace_*.txt", "gcdeadtrace_*.log", "*_stderr.log"} {
				pattern := filepath.Join(dir, ext)
				matches, err := filepath.Glob(pattern)
				if err == nil {
					inputFiles = append(inputFiles, matches...)
				}
			}
		}
		inputFiles = unique(inputFiles)
		if len(inputFiles) == 0 {
			fmt.Println("  No gcdeadtrace_*.txt / gcdeadtrace_*.log files found in ./ or output/")
			os.Exit(1)
		}
	}

	var allData []*ParsedData
	for _, inPath := range inputFiles {
		if _, err := os.Stat(inPath); os.IsNotExist(err) {
			fmt.Printf("  [SKIP] file not found: %s\n", inPath)
			continue
		}
		label := strings.TrimSuffix(filepath.Base(inPath), ".log")
		label = strings.TrimSuffix(label, ".txt")
		fmt.Printf("  Parsing %s ... ", label)
		data := parseFile(inPath)
		allData = append(allData, data)
		if len(data.GCCycles) > 0 {
			maxSess := 0
			for _, gc := range data.GCCycles {
				if len(gc.Sessions) > maxSess { maxSess = len(gc.Sessions) }
			}
			fmt.Printf("%d GC cycles, up to %d sessions/cycle\n", len(data.GCCycles), maxSess)
		} else {
			fmt.Println("0 GC cycles")
		}
	}

	if len(allData) == 0 {
		fmt.Println("  No data to process.")
		os.Exit(1)
	}

	builder := xlsxBuilder{}
	builder.sheets = append(builder.sheets, *buildOverviewSheet(allData))
	for _, d := range allData {
		builder.sheets = append(builder.sheets, *buildModeSheet(d))
	}

	outPath := "gcdeadtrace_report_lifecycle.xlsx"
	fmt.Printf("\n  Writing %s ... ", outPath)
	if err := builder.writeXLSX(outPath); err != nil {
		fmt.Printf("ERROR: %v\n", err)
		os.Exit(1)
	}
	info, _ := os.Stat(outPath)
	fmt.Printf("done (%d bytes)\n", info.Size())
	fmt.Printf("\n  %d file(s) → %d sheet(s)\n", len(inputFiles), len(builder.sheets))
	fmt.Println("  Open gcdeadtrace_report_lifecycle.xlsx in Excel.")
}

// unique deduplicates a string slice while preserving order.
func unique(s []string) []string {
	seen := make(map[string]bool, len(s))
	r := make([]string, 0, len(s))
	for _, v := range s {
		if seen[v] {
			continue
		}
		seen[v] = true
		r = append(r, v)
	}
	return r
}
