// excel_report_lifecycle — gcdeadtrace demo XLSX report generator with
// short-lived vs session-lifetime object lifecycle analysis.
//
// Extends the base excel_report.go by identifying which GC cycles correspond
// to "before session end" (short-lived freed) and "after session end"
// (session-lifetime freed), then producing cross-referenced per-site tables.
//
// Usage:
//   excel_report_lifecycle.exe [file1.txt file2.txt ...]
//
//   If no arguments are given, scans the current directory and output/
//   subdirectory for gcdeadtrace_*.txt / gcdeadtrace_*.log files automatically.
//   Otherwise, processes the specified files in the given order.
//   Each file becomes one sheet (named by its filename without .txt prefix).
//
// Output:
//   output/gcdeadtrace_report_lifecycle.xlsx — multi-sheet Excel workbook
//
// Build:
//   go build -o excel_report_lifecycle.exe excel_report_lifecycle.go
//
// Prerequisites:
//   - Input files generated by demo.exe with GODEBUG=gcdeadtrace=1
//   - No external Go dependencies (uses only archive/zip + encoding/xml)
package main

import (
	"archive/zip"
	"bufio"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// ── data types ─────────────────────────────────────────────────────

type SessionEntry struct {
	ID, GID, Generation             int
	Allocs, AllocBytes              int
	Frees, FreeBytes                int
	Alive, AliveBytes               int
	Start, End                      string
	GidBreakdown                    []GidEntry
}

type GidEntry struct {
	GID                int
	Allocs, AllocBytes int
	Frees, FreeBytes   int
}

type FreedAlive struct {
	Objs, Bytes, Sites int
}

type SiteLine struct {
	Func, Loc string
	Objs, Bytes int
	Refs       string
}

type GCBlock struct {
	GC                          int
	Sessions                    []SessionEntry
	Freed                       *FreedAlive
	Alive                       *FreedAlive
	FreedSites, AliveSites      []SiteLine
}

type ParsedData struct {
	Mode    string
	GCCycles []GCBlock
	// RunStart holds GCCycles indices where a new run begins, detected when
	// the GC number resets (e.g. process restarted with output appended to
	// the same file). Empty means the file contains a single run.
	RunStart []int
}

// ── parsing ────────────────────────────────────────────────────────

var (
	// session #1003: 3 allocs (1328 bytes), 0 freed (0 bytes), 3 alive (1328 bytes) [first: main.go:361 (gid=10), end: main.go:372]
	sessionRe = regexp.MustCompile(
		`\s*session (#\d+(?:#\d+)?):\s*(\d+) allocs \((\d+) bytes\),\s*(\d+) freed \((\d+) bytes\),\s*(\d+) alive \((\d+) bytes\)` +
			`(?:\s*\[first: (.+?) \(gid=(\d+)\)(.*?)\])?`,
	)
	endRe = regexp.MustCompile(`, end: (\S+)`)
	freedSumRe = regexp.MustCompile(`gcdeadsession:freed:\s*(\d+) session objs \((\d+) bytes\) freed from (\d+) sites`)
	aliveSumRe = regexp.MustCompile(`gcdeadsession:alive:\s*(\d+) session objs \((\d+) bytes\) still alive from (\d+) sites`)
	gcHeaderRe = regexp.MustCompile(`=== GC #(\d+) ===`)
	siteLineRe = regexp.MustCompile(`\s+(.+) \((\S+:\d+)\).*:\s*(\d+) session objs, (\d+) session bytes\s+(.*)`)
	gidBreakRe = regexp.MustCompile(`\s+gid=(\d+):\s*(\d+) allocs \((\d+) bytes\),\s*(\d+) freed \((\d+) bytes\)`)
)

func parseInt(s string) int {
	n, _ := strconv.Atoi(s)
	return n
}

// sessionKey builds a unique display key for a (baseID, generation) pair.
// Gen 0 sessions use just the ID; gen > 0 use "ID#gen".
func sessionKey(id, gen int) string {
	if gen == 0 {
		return fmt.Sprintf("%d", id)
	}
	return fmt.Sprintf("%d#%d", id, gen)
}

// sessionDisplay formats a session key for display (e.g. "#9001", "#9001#1").
func sessionDisplay(key string) string {
	return "#" + key
}

func parseFile(path string) *ParsedData {
	f, _ := os.Open(path)
	defer f.Close()
	base := strings.TrimSuffix(filepath.Base(path), ".log")
	base = strings.TrimSuffix(base, ".txt")
	mode := strings.TrimPrefix(base, "gcdeadtrace_demo_")
	data := &ParsedData{Mode: mode}
	scanner := bufio.NewScanner(f)
	var lines []string
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}
	i := 0
	for i < len(lines) && !gcHeaderRe.MatchString(lines[i]) {
		i++
	}
	prevGC := -1
	for i < len(lines) {
		m := gcHeaderRe.FindStringSubmatch(lines[i])
		if m == nil { i++; continue }
		gcNum := parseInt(m[1])
		// GC number going backwards means a new run was appended to the file.
		if prevGC >= 0 && gcNum < prevGC {
			data.RunStart = append(data.RunStart, len(data.GCCycles))
		}
		prevGC = gcNum
		i++
		block := GCBlock{GC: gcNum}
		for i < len(lines) && !gcHeaderRe.MatchString(lines[i]) {
			line := lines[i]
			if sm := sessionRe.FindStringSubmatch(line); sm != nil {
				rawID := strings.TrimPrefix(sm[1], "#")
				gen := 0
				if genIdx := strings.Index(rawID, "#"); genIdx >= 0 {
					gen = parseInt(rawID[genIdx+1:])
					rawID = rawID[:genIdx]
				}
				se := SessionEntry{
					ID: parseInt(rawID), Generation: gen,
					Allocs: parseInt(sm[2]), AllocBytes: parseInt(sm[3]),
					Frees: parseInt(sm[4]), FreeBytes: parseInt(sm[5]),
					Alive: parseInt(sm[6]), AliveBytes: parseInt(sm[7]),
				}
				// Extract [first: ... (gid=N), ...] from inline continuation
				if sm[8] != "" {
					se.Start = sm[8]           // e.g. "main.go:361"
					se.GID = parseInt(sm[9])    // e.g. 18
					if em := endRe.FindStringSubmatch(sm[10]); em != nil {
						se.End = em[1]          // e.g. "main.go:372"
					}
				}
				block.Sessions = append(block.Sessions, se)
				i++
				// Parse subsequent gid breakdown lines
				for i < len(lines) {
					if gm := gidBreakRe.FindStringSubmatch(lines[i]); gm != nil {
						se.GidBreakdown = append(se.GidBreakdown, GidEntry{
							GID: parseInt(gm[1]), Allocs: parseInt(gm[2]),
							AllocBytes: parseInt(gm[3]), Frees: parseInt(gm[4]),
							FreeBytes: parseInt(gm[5]),
						})
						i++
						continue
					}
					break
				}
				continue
			}
			if fm := freedSumRe.FindStringSubmatch(line); fm != nil {
				block.Freed = &FreedAlive{Objs: parseInt(fm[1]), Bytes: parseInt(fm[2]), Sites: parseInt(fm[3])}
				i++
				for i < len(lines) {
					sl := siteLineRe.FindStringSubmatch(lines[i])
					if sl == nil { break }
					block.FreedSites = append(block.FreedSites, SiteLine{strings.TrimSpace(sl[1]), sl[2], parseInt(sl[3]), parseInt(sl[4]), strings.TrimSpace(sl[5])})
					i++
				}
				continue
			}
			if am := aliveSumRe.FindStringSubmatch(line); am != nil {
				block.Alive = &FreedAlive{Objs: parseInt(am[1]), Bytes: parseInt(am[2]), Sites: parseInt(am[3])}
				i++
				for i < len(lines) {
					sl := siteLineRe.FindStringSubmatch(lines[i])
					if sl == nil { break }
					block.AliveSites = append(block.AliveSites, SiteLine{strings.TrimSpace(sl[1]), sl[2], parseInt(sl[3]), parseInt(sl[4]), strings.TrimSpace(sl[5])})
					i++
				}
				continue
			}
			i++
		}
		data.GCCycles = append(data.GCCycles, block)
	}
	return data
}

// ── XLSX builder ──────────────────────────────────────────────────

type xlsxSheet struct {
	name      string
	rows      [][]string
	colWidths []float64
}

const maxColWidth = 70.0

func (s *xlsxSheet) addRow(cells ...string) {
	s.rows = append(s.rows, cells)
	for i, c := range cells {
		w := float64(len(c)) * 1.05
		if w < 10 { w = 10 }
		if w > maxColWidth { w = maxColWidth }
		if w > s.colWidths[i] { s.colWidths[i] = w }
	}
}

func (s *xlsxSheet) addBlank() {
	s.rows = append(s.rows, nil)
}

func (s *xlsxSheet) addHeaderRow(cells ...string) {
	s.rows = append(s.rows, cells)
}

func escXML(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, "\"", "&quot;")
	return s
}

func colLetter(i int) string {
	return string(rune('A' + i))
}

func fmtFloat(f float64) string {
	if f == math.Trunc(f) {
		return fmt.Sprintf("%.0f", f)
	}
	return fmt.Sprintf("%.1f", f)
}

func trimSheetName(name string, used map[string]bool) string {
	const maxLen = 31
	runes := []rune(name)
	if len(runes) <= maxLen && !used[name] {
		used[name] = true
		return name
	}
	base := string(runes[:min(len(runes), maxLen)])
	if !used[base] {
		used[base] = true
		return base
	}
	for n := 2; ; n++ {
		suffix := fmt.Sprintf("(%d)", n)
		suffixRunes := len([]rune(suffix))
		avail := maxLen - suffixRunes
		if avail < 0 { avail = 0 }
		candidate := string(runes[:min(len(runes), avail)]) + suffix
		if !used[candidate] {
			used[candidate] = true
			return candidate
		}
	}
}

func (xb *xlsxBuilder) writeXLSX(path string) error {
	// Trim and deduplicate sheet names (Excel 31-char limit).
	used := make(map[string]bool)
	for i := range xb.sheets {
		xb.sheets[i].name = trimSheetName(xb.sheets[i].name, used)
	}

	f, err := os.Create(path)
	if err != nil { return err }
	defer f.Close()

	w := zip.NewWriter(f)
	defer w.Close()

	// [Content_Types].xml
	ct := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
  <Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/>`
	for i := range xb.sheets {
		ct += fmt.Sprintf("\n  <Override PartName=\"/xl/worksheets/sheet%d.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet.xml\"/>", i+1)
	}
	ct += "\n</Types>"
	xb.writeFile(w, "[Content_Types].xml", ct)

	// _rels/.rels
	rels := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>`
	xb.writeFile(w, "_rels/.rels", rels)

	// xl/workbook.xml
	wb := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
          xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>`
	for i, s := range xb.sheets {
		wb += fmt.Sprintf("\n    <sheet name=\"%s\" sheetId=\"%d\" r:id=\"rId%d\"/>", escXML(s.name), i+1, i+3)
	}
	wb += "\n  </sheets>\n</workbook>"
	xb.writeFile(w, "xl/workbook.xml", wb)

	// xl/_rels/workbook.xml.rels
	wbRels := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>`
	for i := range xb.sheets {
		wbRels += fmt.Sprintf("\n  <Relationship Id=\"rId%d\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet%d.xml\"/>", i+3, i+1)
	}
	wbRels += "\n</Relationships>"
	xb.writeFile(w, "xl/_rels/workbook.xml.rels", wbRels)

	// xl/styles.xml — bold header font
	styles := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <fonts count="2">
    <font><sz val="11"/><name val="Consolas"/></font>
    <font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Consolas"/></font>
  </fonts>
  <fills count="3">
    <fill><patternFill patternType="none"/></fill>
    <fill><patternFill patternType="gray125"/></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FF4472C4"/></patternFill></fill>
  </fills>
  <borders count="2">
    <border><left/><right/><top/><bottom/><diagonal/></border>
    <border>
      <left style="thin"><color auto="1"/></left>
      <right style="thin"><color auto="1"/></right>
      <top style="thin"><color auto="1"/></top>
      <bottom style="thin"><color auto="1"/></bottom>
      <diagonal/>
    </border>
  </borders>
  <cellStyleXfs count="1">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0"/>
  </cellStyleXfs>
  <cellXfs count="4">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
    <xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center"/></xf>
    <xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1"/>
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyFont="1"><font><b/><sz val="12"/><name val="Consolas"/></font></xf>
  </cellXfs>
</styleSheet>`
	xb.writeFile(w, "xl/styles.xml", styles)

	// xl/sharedStrings.xml
	ss := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="0" uniqueCount="0"></sst>`
	xb.writeFile(w, "xl/sharedStrings.xml", ss)

	// xl/worksheets/sheetN.xml
	for si, sheet := range xb.sheets {
		colXml := "<cols>"
		for i, w := range sheet.colWidths {
			if w > 0 {
				colXml += fmt.Sprintf("<col min=\"%d\" max=\"%d\" width=\"%.1f\" customWidth=\"1\"/>", i+1, i+1, w)
			}
		}
		colXml += "</cols>"

		rowsXml := ""
		inSection := false
		for ri, row := range sheet.rows {
			if row == nil {
				rowsXml += fmt.Sprintf("<row r=\"%d\"></row>", ri+1)
				inSection = false
				continue
			}
			styleIdx := 0
			if !inSection {
				styleIdx = 1 // blue bold header
			} else {
				styleIdx = 2 // bordered data
			}
			if len(row) > 0 && (strings.HasPrefix(row[0], "==") || row[0] == "Mode:" || strings.HasPrefix(row[0], "Session #")) {
				styleIdx = 3 // section title
			}
			inSection = true

			rowsXml += fmt.Sprintf("<row r=\"%d\">", ri+1)
			for ci, cell := range row {
				ref := fmt.Sprintf("%s%d", colLetter(ci), ri+1)
				if cell == "" {
					rowsXml += fmt.Sprintf("<c r=\"%s\" s=\"%d\"/>", ref, styleIdx)
					continue
				}
				if n, err := strconv.Atoi(cell); err == nil {
					rowsXml += fmt.Sprintf("<c r=\"%s\" s=\"%d\"><v>%d</v></c>", ref, styleIdx, n)
				} else if f, err := strconv.ParseFloat(cell, 64); err == nil {
					rowsXml += fmt.Sprintf("<c r=\"%s\" s=\"%d\"><v>%s</v></c>", ref, styleIdx, fmtFloat(f))
				} else {
					rowsXml += fmt.Sprintf("<c r=\"%s\" t=\"inlineStr\" s=\"%d\"><is><t>%s</t></is></c>", ref, styleIdx, escXML(cell))
				}
			}
			rowsXml += "</row>"
		}

		sheetXml := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
           xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  %s
  <sheetData>%s</sheetData>
</worksheet>`, colXml, rowsXml)

		xb.writeFile(w, fmt.Sprintf("xl/worksheets/sheet%d.xml", si+1), sheetXml)
	}

	return nil
}

type xlsxBuilder struct {
	sheets []xlsxSheet
}

func (xb *xlsxBuilder) writeFile(w *zip.Writer, name, content string) {
	f, _ := w.Create(name)
	f.Write([]byte(content))
}

// ── build sheets from parsed data ─────────────────────────────────

type sessAgg struct {
	GID, FirstGC, LastGC            int
	Start, End                      string
	CumAllocs, CumAllocBytes        int
	CumFrees, CumFreeBytes          int
	MaxAlive, MaxAliveBytes         int
}

func buildOverviewSheet(allData []*ParsedData) *xlsxSheet {
	s := &xlsxSheet{name: "Overview", colWidths: make([]float64, 20)}
	s.addHeaderRow("Mode", "GC Cycles", "Sessions", "Freed Objs", "Freed Bytes", "Alive Objs", "Alive Bytes", "Avg Freed/GC", "Avg Alive/GC")
	for _, d := range allData {
		tf := 0
		tfBytes := 0
		for _, gc := range d.GCCycles {
			if gc.Freed != nil { tf += gc.Freed.Objs; tfBytes += gc.Freed.Bytes }
		}
		ta := 0
		taBytes := 0
		for i := len(d.GCCycles) - 1; i >= 0; i-- {
			if d.GCCycles[i].Alive != nil {
				ta = d.GCCycles[i].Alive.Objs
				taBytes = d.GCCycles[i].Alive.Bytes
				break
			}
		}
		sessSet := make(map[int]bool)
		for _, gc := range d.GCCycles {
			for _, se := range gc.Sessions { sessSet[se.ID] = true }
		}
		gcN := len(d.GCCycles)
		s.addRow(d.Mode, fmt.Sprint(gcN), fmt.Sprint(len(sessSet)),
			fmt.Sprint(tf), fmt.Sprintf("%d (%.2f MB)", tfBytes, float64(tfBytes)/1024/1024),
			fmt.Sprint(ta), fmt.Sprintf("%d (%.2f MB)", taBytes, float64(taBytes)/1024/1024),
			fmt.Sprintf("%.1f", float64(tf)/float64(gcN)),
			fmt.Sprintf("%.1f", float64(ta)/float64(gcN)))
	}
	return s
}

// ── Lifecycle analysis helpers ────────────────────────────────────

// LifecycleAnalysis holds the per-site breakdown for a single session's lifecycle.
type LifecycleAnalysis struct {
	SessionID int
	EndLoc    string

	// End-triggered GC (first end-marked appearance): the session's final
	// in-session snapshot. Short-lived = all frees up to and including it;
	// session-lifetime candidates = its alive set.
	BeforeEndGC      int
	ShortLivedFreed  []SiteLine // all frees ≤ end-triggered GC (aggregated)
	SessionLifetimeAlive []SiteLine // alive at the end-triggered GC

	// Post-session: all frees after the end-triggered GC (aggregated);
	// Runtime-Persistent baseline = alive at the final GC.
	AfterEndGC           int
	SessionLifetimeFreed []SiteLine // all frees > end-triggered GC (aggregated)
	FinalAlive           []SiteLine // alive at the final GC (Runtime-Persistent baseline)

	// Cross-reference: alive sites that were also freed after end = session-lifetime objects.
	MatchedSites  []SiteMatch
	NotFreedSites []SiteLine // alive sites not found in after-end freed (potentially leaked)
}

type SiteMatch struct {
	Site      SiteLine
	FreedObjs int
	FreedBytes int
	AliveObjs int
	AliveBytes int
}

// siteInfo aggregates per-site attribution across GC cycles.
type siteInfo struct {
	Func, Loc          string
	TotalObjs, TotalBytes int
	Refs               map[string]bool
}

// AggLifecycle aggregates lifecycle analysis across all detected lifecycle sessions.
type AggLifecycle struct {
	SessionCount int
	Sessions     []int
	ShortLived   map[string]*siteInfo
	SessLifetime map[string]*siteInfo
	LateAlloc    map[string]*siteInfo
	NotFreed     map[string]*siteInfo
}

// filterSitesBySession filters per-site data to only include contributions
// from the target session ID. Parses the Refs string to extract per-session counts,
// including overflow markers ([+N objs from other sessions]) when the target session
// is the only session referenced by this site.
func filterSitesBySession(sites []SiteLine, sessionID int) []SiteLine {
	targetKey := fmt.Sprintf("session #%d:", sessionID)
	overflowReNew := regexp.MustCompile(`\[\+(\d+) objs, (\d+) bytes from other sessions\]`)
	overflowReOld := regexp.MustCompile(`\[\+(\d+) objs from other sessions\]`)
	var filtered []SiteLine
	for _, site := range sites {
		var totalObjs, totalBytes int
		refs := site.Refs
		onlyTarget := true
		for {
			idx := strings.Index(refs, targetKey)
			if idx < 0 {
				break
			}
			rest := refs[idx+len(targetKey):]
			end := strings.Index(rest, "]")
			if end < 0 {
				break
			}
			// Parse " N objs, B bytes @type (gid=G)" or " N objs, B bytes (gid=G)"
			part := strings.TrimSpace(rest[:end])
			fields := strings.SplitN(part, " ", 4)
			if len(fields) >= 4 {
				objs, _ := strconv.Atoi(fields[0])
				bytes, _ := strconv.Atoi(fields[2])
				totalObjs += objs
				totalBytes += bytes
			}
			refs = rest[end+1:]
		}
		// Check if there are any other session IDs referenced on this site.
		otherRe := regexp.MustCompile(`\[session #\d+:`)
		allRefs := otherRe.FindAllString(site.Refs, -1)
		for _, r := range allRefs {
			if r != "[session #"+strconv.Itoa(sessionID)+":" {
				onlyTarget = false
				break
			}
		}
		// If only target session is referenced, include overflow objs.
		if onlyTarget {
			if om := overflowReNew.FindStringSubmatch(site.Refs); om != nil {
				overflowObjs, _ := strconv.Atoi(om[1])
				overflowBytes, _ := strconv.Atoi(om[2])
				totalObjs += overflowObjs
				totalBytes += overflowBytes
			} else if om := overflowReOld.FindStringSubmatch(site.Refs); om != nil {
				overflowObjs, _ := strconv.Atoi(om[1])
				totalObjs += overflowObjs
				// Old format: no bytes in overflow marker, bytes will be underestimated.
			}
		}
		if totalObjs > 0 || totalBytes > 0 {
			filtered = append(filtered, SiteLine{
				Func:  site.Func,
				Loc:   site.Loc,
				Objs:  totalObjs,
				Bytes: totalBytes,
				Refs:  site.Refs,
			})
		}
	}
	return filtered
}

// analyzeLifecycle performs the GC orchestration analysis for a given session ID.
// Returns nil if no lifecycle pattern is detected for the session.
//
// GC semantics: the FIRST GC where the session appears WITH an end marker is
// the end-triggered GC (GcDeadSessionEnd forces a runtime.GC) — its state is
// the session's final in-session snapshot (会话中/结束点). The SECOND
// end-marked appearance is the first post-session GC (会话结束), where
// session-lifetime objects start decaying.
func analyzeLifecycle(gcs []GCBlock, sessionID int, runStart []int) *LifecycleAnalysis {
	var la LifecycleAnalysis
	la.SessionID = sessionID

	// Locate the end-triggered GC (first appearance with end marker).
	endIdx := -1
	for gi, gc := range gcs {
		for _, se := range gc.Sessions {
			if se.ID == sessionID && se.End != "" {
				if endIdx < 0 {
					endIdx = gi
					la.EndLoc = se.End
				}
			}
		}
	}
	if endIdx < 0 {
		return nil // no end marker — session still running or no lifecycle pattern
	}

	// Bound analysis to the session's own run (a file may hold multiple
	// concatenated runs; other runs contain no data for this session).
	runBegin, runEnd := 0, len(gcs)
	for _, rs := range runStart {
		if rs <= endIdx {
			runBegin = rs
		} else {
			runEnd = rs
			break
		}
	}

	la.BeforeEndGC = gcs[endIdx].GC
	// Short-lived: all frees up to and including the end GC (aggregated per site).
	for gi := runBegin; gi <= endIdx; gi++ {
		la.ShortLivedFreed = append(la.ShortLivedFreed, filterSitesBySession(gcs[gi].FreedSites, sessionID)...)
	}
	// Session-lifetime candidates: alive at the end GC.
	la.SessionLifetimeAlive = filterSitesBySession(gcs[endIdx].AliveSites, sessionID)
	// Post-session frees: all frees after the end GC within this run (aggregated per site).
	for gi := endIdx + 1; gi < runEnd; gi++ {
		la.SessionLifetimeFreed = append(la.SessionLifetimeFreed, filterSitesBySession(gcs[gi].FreedSites, sessionID)...)
	}
	// After-end GC (display): the next GC after the end-triggered one.
	if endIdx+1 < runEnd {
		la.AfterEndGC = gcs[endIdx+1].GC
	}
	// Runtime-Persistent baseline: alive at this run's final GC with alive data.
	for gi := runEnd - 1; gi >= runBegin; gi-- {
		if len(gcs[gi].AliveSites) > 0 {
			la.FinalAlive = filterSitesBySession(gcs[gi].AliveSites, sessionID)
			break
		}
	}

	// Cross-reference: session-lifetime alive sites (from before-end GC) vs freed after end.
	type siteKey struct{ funcName, loc string }
	aliveByKey := make(map[siteKey]SiteLine)
	for _, site := range la.SessionLifetimeAlive {
		key := siteKey{firstFileLine(site.Func, site.Loc), site.Loc}
		if existing, ok := aliveByKey[key]; ok {
			existing.Objs += site.Objs
			existing.Bytes += site.Bytes
			aliveByKey[key] = existing
		} else {
			aliveByKey[key] = site
		}
	}

	freedByKey := make(map[siteKey]SiteLine)
	for _, site := range la.SessionLifetimeFreed {
		key := siteKey{firstFileLine(site.Func, site.Loc), site.Loc}
		if existing, ok := freedByKey[key]; ok {
			existing.Objs += site.Objs
			existing.Bytes += site.Bytes
			freedByKey[key] = existing
		} else {
			freedByKey[key] = site
		}
	}

	// Matched: alive site that appears in after-end freed = session-lifetime.
	for key, alive := range aliveByKey {
		if freed, ok := freedByKey[key]; ok {
			la.MatchedSites = append(la.MatchedSites, SiteMatch{
				Site:       alive,
				AliveObjs:  alive.Objs,
				AliveBytes: alive.Bytes,
				FreedObjs:  freed.Objs,
				FreedBytes: freed.Bytes,
			})
		}
	}
	sort.Slice(la.MatchedSites, func(i, j int) bool {
		return la.MatchedSites[i].AliveBytes > la.MatchedSites[j].AliveBytes
	})

	// Not freed: alive site not found in after-end freed (potentially leaked or runtime).
	for key, alive := range aliveByKey {
		if _, ok := freedByKey[key]; !ok {
			la.NotFreedSites = append(la.NotFreedSites, alive)
		}
	}
	sort.Slice(la.NotFreedSites, func(i, j int) bool {
		return la.NotFreedSites[i].Bytes > la.NotFreedSites[j].Bytes
	})

	return &la
}

// sessGCInfo tracks end-marker appearances for lifecycle detection.
type sessGCInfo struct {
	sawNoEnd bool // session seen without end marker (in-session phase visible)
	endCount int  // appearances with end marker
}

// findLifecycleSessions finds session IDs with the lifecycle pattern:
// a visible in-session phase (>=1 appearance without end) and >=2
// end-marked appearances (first = end-triggered GC snapshot, second =
// first post-session GC).
func findLifecycleSessions(gcs []GCBlock) []int {
	info := make(map[int]*sessGCInfo)
	for _, gc := range gcs {
		for _, se := range gc.Sessions {
			si := info[se.ID]
			if si == nil {
				si = &sessGCInfo{}
				info[se.ID] = si
			}
			if se.End == "" {
				si.sawNoEnd = true
			} else {
				si.endCount++
			}
		}
	}
	var result []int
	for id, si := range info {
		if si.sawNoEnd && si.endCount >= 2 {
			result = append(result, id)
		}
	}
	sort.Ints(result)
	return result
}

// aggregateLifecycles detects all lifecycle sessions and aggregates their
// per-site data into a single AggLifecycle. Returns nil if no lifecycle
// sessions are found.
func aggregateLifecycles(gcs []GCBlock, runStart []int) *AggLifecycle {
	sessions := findLifecycleSessions(gcs)
	if len(sessions) == 0 {
		return nil
	}

	agg := &AggLifecycle{
		SessionCount: len(sessions),
		Sessions:     sessions,
		ShortLived:   make(map[string]*siteInfo),
		SessLifetime: make(map[string]*siteInfo),
		LateAlloc:    make(map[string]*siteInfo),
		NotFreed:     make(map[string]*siteInfo),
	}

	for _, sid := range sessions {
		la := analyzeLifecycle(gcs, sid, runStart)
		if la == nil {
			continue
		}

		// ShortLived: aggregate ShortLivedFreed sites.
		for _, site := range la.ShortLivedFreed {
			key := site.Func + "|" + site.Loc
			si, ok := agg.ShortLived[key]
			if !ok {
				si = &siteInfo{Func: site.Func, Loc: site.Loc, Refs: make(map[string]bool)}
				agg.ShortLived[key] = si
			}
			si.TotalObjs += site.Objs
			si.TotalBytes += site.Bytes
			si.Refs[site.Refs] = true
		}

		// SessLifetime: aggregate MatchedSites (using FreedObjs/FreedBytes).
		for _, m := range la.MatchedSites {
			key := m.Site.Func + "|" + m.Site.Loc
			si, ok := agg.SessLifetime[key]
			if !ok {
				si = &siteInfo{Func: m.Site.Func, Loc: m.Site.Loc, Refs: make(map[string]bool)}
				agg.SessLifetime[key] = si
			}
			si.TotalObjs += m.FreedObjs
			si.TotalBytes += m.FreedBytes
			si.Refs[m.Site.Refs] = true
		}

		// LateAlloc: SessionLifetimeFreed NOT in MatchedSites.
		// Use same normalized key (firstFileLine+Loc) as analyzeLifecycle siteKey.
		matchedKey := make(map[string]bool)
		for _, m := range la.MatchedSites {
			key := firstFileLine(m.Site.Func, m.Site.Loc) + "|" + m.Site.Loc
			matchedKey[key] = true
		}
		for _, site := range la.SessionLifetimeFreed {
			key := firstFileLine(site.Func, site.Loc) + "|" + site.Loc
			if !matchedKey[key] {
				aggKey := site.Func + "|" + site.Loc
				si, ok := agg.LateAlloc[aggKey]
				if !ok {
					si = &siteInfo{Func: site.Func, Loc: site.Loc, Refs: make(map[string]bool)}
					agg.LateAlloc[aggKey] = si
				}
				si.TotalObjs += site.Objs
				si.TotalBytes += site.Bytes
				si.Refs[site.Refs] = true
			}
		}

		// NotFreed (Runtime-Persistent): aggregate after-end alive sites.
		for _, site := range la.FinalAlive {
			key := site.Func + "|" + site.Loc
			si, ok := agg.NotFreed[key]
			if !ok {
				si = &siteInfo{Func: site.Func, Loc: site.Loc, Refs: make(map[string]bool)}
				agg.NotFreed[key] = si
			}
			si.TotalObjs += site.Objs
			si.TotalBytes += site.Bytes
			si.Refs[site.Refs] = true
		}
	}

	return agg
}

// buildSiteSheet creates a standalone sheet from a site attribution map.
// Used for non-lifecycle modes to split freed (短周期) and alive (会话周期) into separate sheets.
func buildSiteSheet(name, title string, siteMap map[string]*siteInfo) *xlsxSheet {
	s := &xlsxSheet{name: name, colWidths: make([]float64, 20)}
	s.addRow(title)
	s.addHeaderRow("Allocation Site", "File:Line", "Total Objs", "Total Bytes", "Session Refs")
	var sites []*siteInfo
	tObjs, tBytes := 0, 0
	for _, si := range siteMap { sites = append(sites, si); tObjs += si.TotalObjs; tBytes += si.TotalBytes }
	sort.Slice(sites, func(i, j int) bool { return sites[i].TotalBytes > sites[j].TotalBytes })
	for _, si := range sites {
		var refs []string
		for r := range si.Refs { refs = append(refs, r) }
		sort.Strings(refs)
		refStr := strings.Join(refs, "; ")
		if len(refStr) > 10000 { refStr = refStr[:9997] + "..." }
		loc := firstFileLine(si.Func, si.Loc)
		s.addRow(si.Func, loc, fmt.Sprint(si.TotalObjs), fmt.Sprint(si.TotalBytes), refStr)
	}
	return s
}

// ── build mode sheet with lifecycle analysis ──────────────────────

func buildModeSheet(data *ParsedData) []*xlsxSheet {
	s := &xlsxSheet{name: data.Mode, colWidths: make([]float64, 20)}
	var extraSheets []*xlsxSheet
	gcs := data.GCCycles

	// Run boundaries: a GC-number reset (e.g. process restart appended to the
	// same file) starts a new run. Alive is per-run final state, summed across
	// runs; freed/alloc are additive across everything.
	rb := append([]int{0}, data.RunStart...)
	rb = append(rb, len(gcs))

	tf := 0
	tfBytes := 0
	for _, gc := range gcs {
		if gc.Freed != nil { tf += gc.Freed.Objs; tfBytes += gc.Freed.Bytes }
	}
	ta := 0
	taBytes := 0
	for r := 0; r+1 < len(rb); r++ {
		for i := rb[r+1] - 1; i >= rb[r]; i-- {
			if gcs[i].Alive != nil {
				ta += gcs[i].Alive.Objs
				taBytes += gcs[i].Alive.Bytes
				break
			}
		}
	}
	sessSet := make(map[string]bool)
	for _, gc := range gcs {
		for _, se := range gc.Sessions { sessSet[sessionKey(se.ID, se.Generation)] = true }
	}

	// siteInfo struct for site attribution aggregation.
	type sInfo struct {
		Func, Loc          string
		TotalObjs, TotalBytes int
		Refs               map[string]bool
	}

	// ── Pre-compute summary statistics for the top-of-sheet summary ──
	// Freed site totals.
	fSumObjs, fSumBytes := 0, 0
	fSumMap := make(map[string]*sInfo)
	for _, gc := range gcs {
		for _, site := range gc.FreedSites {
			key := site.Func + "|" + site.Loc
			si, ok := fSumMap[key]
			if !ok { si = &sInfo{Func: site.Func, Loc: site.Loc, Refs: make(map[string]bool)}; fSumMap[key] = si }
			si.TotalObjs += site.Objs; si.TotalBytes += site.Bytes
		}
	}
	for _, si := range fSumMap { fSumObjs += si.TotalObjs; fSumBytes += si.TotalBytes }

	// Alive site totals — per-run final GC snapshot, summed across runs
	// (alive is NOT additive across cycles within a run, but each run's
	// final alive is an independent survivor set).
	aSumObjs, aSumBytes := 0, 0
	aSumMap := make(map[string]*sInfo)
	for r := 0; r+1 < len(rb); r++ {
		for i := rb[r+1] - 1; i >= rb[r]; i-- {
			if len(gcs[i].AliveSites) > 0 {
				for _, site := range gcs[i].AliveSites {
					key := site.Func + "|" + site.Loc
					si, ok := aSumMap[key]
					if !ok { si = &sInfo{Func: site.Func, Loc: site.Loc, Refs: make(map[string]bool)}; aSumMap[key] = si }
					si.TotalObjs += site.Objs; si.TotalBytes += site.Bytes
					aSumObjs += site.Objs
					aSumBytes += site.Bytes
				}
				break
			}
		}
	}

	// Cross-reference by file:line for Both/Only counts.
	type sumLineAgg struct {
		FreedObjs, FreedBytes, AliveObjs, AliveBytes int
	}
	fSumByLine := make(map[string]*sumLineAgg)
	aSumByLine := make(map[string]*sumLineAgg)
	for _, si := range fSumMap {
		loc := firstFileLine(si.Func, si.Loc)
		if loc == "" { continue }
		a, ok := fSumByLine[loc]
		if !ok { a = &sumLineAgg{}; fSumByLine[loc] = a }
		a.FreedObjs += si.TotalObjs; a.FreedBytes += si.TotalBytes
	}
	for _, si := range aSumMap {
		loc := firstFileLine(si.Func, si.Loc)
		if loc == "" { continue }
		a, ok := aSumByLine[loc]
		if !ok { a = &sumLineAgg{}; aSumByLine[loc] = a }
		a.AliveObjs += si.TotalObjs; a.AliveBytes += si.TotalBytes
	}
	nBoth, nOnly := 0, 0
	tBFreedObjs, tBFreedBytes, tBAliveObjs, tBAliveBytes := 0, 0, 0, 0
	tOFreedObjs, tOFreedBytes := 0, 0
	for loc := range fSumByLine {
		if _, ok := aSumByLine[loc]; ok {
			nBoth++
			tBFreedObjs += fSumByLine[loc].FreedObjs
			tBFreedBytes += fSumByLine[loc].FreedBytes
			tBAliveObjs += aSumByLine[loc].AliveObjs
			tBAliveBytes += aSumByLine[loc].AliveBytes
		}
	}
	for loc := range fSumByLine {
		if _, ok := aSumByLine[loc]; !ok {
			nOnly++
			tOFreedObjs += fSumByLine[loc].FreedObjs
			tOFreedBytes += fSumByLine[loc].FreedBytes
		}
	}

	// Build sids for session totals (used by both summary and session detail).
	sids := make(map[string]*sessAgg)
	for _, gc := range gcs {
		for _, se := range gc.Sessions {
			sk := sessionKey(se.ID, se.Generation)
			sa, ok := sids[sk]
			if !ok {
				sa = &sessAgg{GID: se.GID, FirstGC: gc.GC, Start: se.Start}
				sids[sk] = sa
			}
			sa.LastGC = gc.GC
			sa.CumAllocs += se.Allocs
			sa.CumAllocBytes += se.AllocBytes
			sa.CumFrees += se.Frees
			sa.CumFreeBytes += se.FreeBytes
			if se.Alive > sa.MaxAlive { sa.MaxAlive = se.Alive; sa.MaxAliveBytes = se.AliveBytes }
			if se.End != "" { sa.End = se.End }
		}
	}
	var sorted []string
	for sk := range sids { sorted = append(sorted, sk) }
	sort.Strings(sorted)

	// Track sessions that appear without end marker (before-end GC).
	beforeEndSessions := make(map[string]bool)
	for _, gc := range gcs {
		for _, se := range gc.Sessions {
			if se.End == "" {
				beforeEndSessions[sessionKey(se.ID, se.Generation)] = true
			}
		}
	}

	// Session totals (from sids).
	sAllocs, sAllocBytes, sFrees, sFreeBytes := 0, 0, 0, 0
	beAllocs, beAllocBytes, beFrees, beFreeBytes, beAlive, beAliveBytes := 0, 0, 0, 0, 0, 0
	for _, id := range sorted {
		sa := sids[id]
		sAllocs += sa.CumAllocs; sAllocBytes += sa.CumAllocBytes
		sFrees += sa.CumFrees; sFreeBytes += sa.CumFreeBytes
		if beforeEndSessions[id] {
			beAllocs += sa.CumAllocs; beAllocBytes += sa.CumAllocBytes
			beFrees += sa.CumFrees; beFreeBytes += sa.CumFreeBytes
		}
	}
	// Per-run stats: session allocs/frees are additive within a run; alive is
	// the run's final GC summary. Unified alive = sum of per-run final alive.
	type runStat struct {
		firstGC, lastGC    int
		allocs, allocBytes int
		frees, freeBytes   int
		alive, aliveBytes  int
	}
	var runs []runStat
	for r := 0; r+1 < len(rb); r++ {
		seg := gcs[rb[r]:rb[r+1]]
		if len(seg) == 0 { continue }
		rs := runStat{firstGC: seg[0].GC, lastGC: seg[len(seg)-1].GC}
		for _, gc := range seg {
			for _, se := range gc.Sessions {
				rs.allocs += se.Allocs; rs.allocBytes += se.AllocBytes
				rs.frees += se.Frees; rs.freeBytes += se.FreeBytes
			}
		}
		for i := len(seg) - 1; i >= 0; i-- {
			if seg[i].Alive != nil {
				rs.alive = seg[i].Alive.Objs
				rs.aliveBytes = seg[i].Alive.Bytes
				break
			}
		}
		runs = append(runs, rs)
	}

	// sLastAlive: unified alive = sum of each run's final-GC alive.
	// beAlive: last GC's alive for before-end sessions only (final run).
	sLastAlive, sLastAliveBytes := 0, 0
	for _, rs := range runs { sLastAlive += rs.alive; sLastAliveBytes += rs.aliveBytes }
	for i := len(gcs) - 1; i >= 0; i-- {
		if gcs[i].Alive != nil {
			for _, se := range gcs[i].Sessions {
				sk := sessionKey(se.ID, se.Generation)
				if beforeEndSessions[sk] {
					beAlive += se.Alive
					beAliveBytes += se.AliveBytes
				}
			}
			break
		}
	}

	// Run lifecycle analysis early so Summary section can reference its data.
	agg := aggregateLifecycles(gcs, data.RunStart)

	// ── Write rows ──
	s.addRow("Mode:", data.Mode)
	s.addRow("GC Cycles:", fmt.Sprint(len(gcs)))
	s.addRow("Sessions:", fmt.Sprint(len(sessSet)))
	s.addRow("Total Freed:", fmt.Sprint(tf))
	s.addRow("Total Freed Bytes:", fmt.Sprintf("%d (%.2f MB)", tfBytes, float64(tfBytes)/1024/1024))
	s.addRow("Total Alive:", fmt.Sprint(ta))
	s.addRow("Total Alive Bytes:", fmt.Sprintf("%d (%.2f MB)", taBytes, float64(taBytes)/1024/1024))
	s.addBlank()

	// Summary block with section-level totals at the top of the sheet.
	s.addRow("=== Summary ===")
	s.addRow("Session Detail (alloc/freed/alive)",
		fmt.Sprintf("%d / %d / %d objs", sAllocs, sFrees, sLastAlive),
		fmt.Sprintf("%s / %s / %s",
			fmt.Sprintf("%d (%.2f MB)", sAllocBytes, float64(sAllocBytes)/1024/1024),
			fmt.Sprintf("%d (%.2f MB)", sFreeBytes, float64(sFreeBytes)/1024/1024),
			fmt.Sprintf("%d (%.2f MB)", sLastAliveBytes, float64(sLastAliveBytes)/1024/1024)),
		"", "")
	// Per-run verification when the file holds multiple runs (GC reset).
	if len(runs) > 1 {
		s.addRow(fmt.Sprintf("检测到 %d 次运行 (GC 编号重置), 分运行验证:", len(runs)), "", "", "", "")
		for i, rs := range runs {
			rMark := "✓"
			if rs.allocs != rs.frees+rs.alive || rs.allocBytes != rs.freeBytes+rs.aliveBytes {
				rMark = fmt.Sprintf("✗ (diff: %d objs, %d bytes)", rs.allocs-rs.frees-rs.alive, rs.allocBytes-rs.freeBytes-rs.aliveBytes)
			}
			s.addRow(fmt.Sprintf("  Run %d (GC #%d-#%d): alloc==freed+alive", i+1, rs.firstGC, rs.lastGC),
				fmt.Sprintf("%d == %d + %d  %s", rs.allocs, rs.frees, rs.alive, rMark),
				fmt.Sprintf("%d == %d + %d  %s", rs.allocBytes, rs.freeBytes, rs.aliveBytes, rMark),
				"", "")
		}
	}
	// Session-level verification: allocs == frees + alive (session invariant).
	sfMatch := "✓"
	if sAllocs != sFrees+sLastAlive || sAllocBytes != sFreeBytes+sLastAliveBytes {
		sfMatch = fmt.Sprintf("✗ (diff: %d objs, %d bytes)", sAllocs-sFrees-sLastAlive, sAllocBytes-sFreeBytes-sLastAliveBytes)
	}
	unifiedNote := ""
	if len(runs) > 1 { unifiedNote = fmt.Sprintf(" (%d 次运行汇总)", len(runs)) }
	s.addRow("  └ 验证: alloc==freed+alive"+unifiedNote,
		fmt.Sprintf("%d == %d + %d  %s", sAllocs, sFrees, sLastAlive, sfMatch),
		fmt.Sprintf("%d == %d + %d  %s", sAllocBytes, sFreeBytes, sLastAliveBytes, sfMatch),
		"", "")
	s.addRow("Before-End Session Detail (alloc/freed/alive)",
		fmt.Sprintf("%d / %d / %d objs", beAllocs, beFrees, beAlive),
		fmt.Sprintf("%s / %s / %s",
			fmt.Sprintf("%d (%.2f MB)", beAllocBytes, float64(beAllocBytes)/1024/1024),
			fmt.Sprintf("%d (%.2f MB)", beFreeBytes, float64(beFreeBytes)/1024/1024),
			fmt.Sprintf("%d (%.2f MB)", beAliveBytes, float64(beAliveBytes)/1024/1024)),
		fmt.Sprintf("(%d sessions)", len(beforeEndSessions)), "")
	s.addRow("Freed Sites",
		fmt.Sprintf("%d lines, %d objs", len(fSumMap), fSumObjs),
		fmt.Sprintf("%d (%.2f MB)", fSumBytes, float64(fSumBytes)/1024/1024),
		"", "")
	s.addRow("Alive Sites",
		fmt.Sprintf("%d lines, %d objs", len(aSumMap), aSumObjs),
		fmt.Sprintf("%d (%.2f MB)", aSumBytes, float64(aSumBytes)/1024/1024),
		"", "")
	s.addRow("Both Freed & Alive",
		fmt.Sprintf("%d lines (%d freed, %d alive)", nBoth, tBFreedObjs, tBAliveObjs),
		fmt.Sprintf("freed %s / alive %s",
			fmt.Sprintf("%d (%.2f MB)", tBFreedBytes, float64(tBFreedBytes)/1024/1024),
			fmt.Sprintf("%d (%.2f MB)", tBAliveBytes, float64(tBAliveBytes)/1024/1024)),
		"", "")
	s.addRow("Site vs Session cross-check (应一致)",
		fmt.Sprintf("freed: sites=%d, session=%d (%s)", fSumObjs, sFrees, checkMatch(fSumObjs, sFrees)),
		fmt.Sprintf("alive: sites=%d, session=%d (%s)", aSumObjs, sLastAlive, checkMatch(aSumObjs, sLastAlive)),
		"", "")
	s.addRow("Only in Freed (fully dead)",
		fmt.Sprintf("%d lines, %d objs", nOnly, tOFreedObjs),
		fmt.Sprintf("%d (%.2f MB)", tOFreedBytes, float64(tOFreedBytes)/1024/1024),
		"", "")

	// 短周期 / 会话周期 / Late-alloc / Runtime-Persistent overview rows.
	var shortObjs, shortBytes, shortLines int
	var sessObjs, sessBytes, sessLines int
	var lateObjs, lateBytes, lateLines int
	var rpObjs, rpBytes, rpLines int
	if agg != nil {
		// 1. 短周期: aggregated ShortLived sites.
		for _, si := range agg.ShortLived { shortObjs += si.TotalObjs; shortBytes += si.TotalBytes }
		shortLines = len(agg.ShortLived)
		// 2. 会话周期: aggregated SessLifetime sites.
		for _, si := range agg.SessLifetime { sessObjs += si.TotalObjs; sessBytes += si.TotalBytes }
		sessLines = len(agg.SessLifetime)
		// 3. Late-alloc freed: aggregated LateAlloc sites.
		for _, si := range agg.LateAlloc { lateObjs += si.TotalObjs; lateBytes += si.TotalBytes }
		lateLines = len(agg.LateAlloc)
		// 4. Runtime-Persistent: aggregated NotFreed sites.
		for _, si := range agg.NotFreed { rpObjs += si.TotalObjs; rpBytes += si.TotalBytes }
		rpLines = len(agg.NotFreed)
	} else {
		// Non-lifecycle: split freed into 短周期/会话周期, all alive → Runtime.
		for key := range fSumMap {
			if _, ok := aSumMap[key]; ok {
				sessObjs += fSumMap[key].TotalObjs
				sessBytes += fSumMap[key].TotalBytes
				sessLines++
			} else {
				shortObjs += fSumMap[key].TotalObjs
				shortBytes += fSumMap[key].TotalBytes
				shortLines++
			}
		}
		// All alive sites → Runtime-Persistent.
		rpObjs = aSumObjs
		rpBytes = aSumBytes
		rpLines = len(aSumMap)
	}
	s.addRow("短周期对象 (Freed Sites, ≤结束GC) → 独立 Sheet",
		fmt.Sprintf("%d lines, %d objs", shortLines, shortObjs),
		fmt.Sprintf("%d (%.2f MB)", shortBytes, float64(shortBytes)/1024/1024),
		"", "")
	s.addRow("会话周期对象 (结束GC存活, 结束后释放) → 独立 Sheet",
		fmt.Sprintf("%d lines, %d objs", sessLines, sessObjs),
		fmt.Sprintf("%d (%.2f MB)", sessBytes, float64(sessBytes)/1024/1024),
		"", "")
	s.addRow("Late-alloc Freed (结束后释放但未匹配到结束点存活) → 独立 Sheet",
		fmt.Sprintf("%d lines, %d objs", lateLines, lateObjs),
		fmt.Sprintf("%d (%.2f MB)", lateBytes, float64(lateBytes)/1024/1024),
		"", "")
	s.addRow("Runtime-Persistent (最终GC仍存活) → 独立 Sheet",
		fmt.Sprintf("%d lines, %d objs", rpLines, rpObjs),
		fmt.Sprintf("%d (%.2f MB)", rpBytes, float64(rpBytes)/1024/1024),
		"", "")
	// Data consistency check: 四类之和 == lifecycle sessions' total allocs.
	total := shortObjs + sessObjs + lateObjs + rpObjs
	totalBytes := shortBytes + sessBytes + lateBytes + rpBytes
	// When agg != nil, validate against lifecycle sessions only (not all sessions).
	checkAllocs, checkAllocBytes := sAllocs, sAllocBytes
	if agg != nil {
		checkAllocs, checkAllocBytes = 0, 0
		lifeSet := make(map[int]bool)
		for _, sid := range agg.Sessions { lifeSet[sid] = true }
		for _, sk := range sorted {
			rawID := sk
			if hashIdx := strings.Index(sk, "#"); hashIdx >= 0 {
				rawID = sk[:hashIdx]
			}
			// Only count gen 0 of each lifecycle session (no # suffix).
			// analyzeLifecycle only processes the first lifecycle pattern per ID,
			// so validation must compare against gen 0 only.
			if lifeSet[parseInt(rawID)] && len(rawID) == len(sk) {
				sa := sids[sk]
				checkAllocs += sa.CumAllocs
				checkAllocBytes += sa.CumAllocBytes
			}
		}
	}
	// 未归属溢出: objects hidden in "[+N objs from other sessions]" overflow
	// markers at multi-session hot sites (16 ref slots per site, filled by
	// other sessions). filterSitesBySession cannot attribute these to the
	// lifecycle session, so they fall out of all four categories.
	unattr := checkAllocs - total
	unattrBytes := checkAllocBytes - totalBytes
	match := "✓"
	if unattr != 0 || unattrBytes != 0 {
		match = fmt.Sprintf("✗ (未归属: %d objs, %d bytes)", unattr, unattrBytes)
	}
	if unattr != 0 || unattrBytes != 0 {
		s.addRow("  未归属溢出 (多session热点site的16槽ref溢出,无法按session归因)",
			fmt.Sprintf("%d objs", unattr),
			fmt.Sprintf("%d (%.2f MB)", unattrBytes, float64(unattrBytes)/1024/1024),
			"", "")
	}
	s.addRow("数据验证: 总分配==短周期+会话周期+LateAlloc+Runtime+未归属溢出",
		fmt.Sprintf("%d == %d + %d + %d + %d + %d = %d  %s", checkAllocs, shortObjs, sessObjs, lateObjs, rpObjs, unattr, total+unattr, match),
		fmt.Sprintf("%d == %d + %d + %d + %d + %d = %d  %s", checkAllocBytes, shortBytes, sessBytes, lateBytes, rpBytes, unattrBytes, totalBytes+unattrBytes, match),
		"", "")
	s.addBlank()

	// Per-GC Summary
	s.addHeaderRow("GC", "Sessions", "Freed Objs", "Freed Bytes", "Alive Objs", "Alive Bytes")
	for _, gc := range gcs {
		fO, fB, aO, aB := "0", "0", "0", "0"
		if gc.Freed != nil { fO = fmt.Sprint(gc.Freed.Objs); fB = fmt.Sprint(gc.Freed.Bytes) }
		if gc.Alive != nil { aO = fmt.Sprint(gc.Alive.Objs); aB = fmt.Sprint(gc.Alive.Bytes) }
		s.addRow(fmt.Sprint(gc.GC), fmt.Sprint(len(gc.Sessions)), fO, fB, aO, aB)
	}
	s.addBlank()

	// Session Detail
	s.addHeaderRow("Session", "GID", "First GC", "Last GC", "Start", "End",
		"Total Allocs", "Alloc Bytes", "Total Frees", "Free Bytes", "Max Alive", "Max Alive Bytes")
	s.addRow("Total", "", "", "", "", "",
		fmt.Sprint(sAllocs), fmt.Sprintf("%d (%.2f MB)", sAllocBytes, float64(sAllocBytes)/1024/1024),
		fmt.Sprint(sFrees), fmt.Sprintf("%d (%.2f MB)", sFreeBytes, float64(sFreeBytes)/1024/1024),
		fmt.Sprint(sLastAlive), fmt.Sprintf("%d (%.2f MB)", sLastAliveBytes, float64(sLastAliveBytes)/1024/1024))
	for _, sk := range sorted {
		sa := sids[sk]
		s.addRow(sessionDisplay(sk), fmt.Sprint(sa.GID),
			fmt.Sprintf("GC#%d", sa.FirstGC), fmt.Sprintf("GC#%d", sa.LastGC),
			shortLoc(sa.Start), shortLoc(sa.End),
			fmt.Sprint(sa.CumAllocs), fmt.Sprint(sa.CumAllocBytes),
			fmt.Sprint(sa.CumFrees), fmt.Sprint(sa.CumFreeBytes),
			fmt.Sprint(sa.MaxAlive), fmt.Sprint(sa.MaxAliveBytes))
	}

	// Session GID Breakdown
	s.addBlank()
	s.addRow("=== Session GID Breakdown ===")
	s.addHeaderRow("Session", "GC", "GID", "Allocs", "Alloc Bytes", "Frees", "Free Bytes")
	for _, gc := range gcs {
		for _, se := range gc.Sessions {
			if len(se.GidBreakdown) > 0 {
				sk := sessionKey(se.ID, se.Generation)
				for _, ge := range se.GidBreakdown {
					s.addRow(sessionDisplay(sk), fmt.Sprintf("GC#%d", gc.GC),
						fmt.Sprint(ge.GID), fmt.Sprint(ge.Allocs), fmt.Sprint(ge.AllocBytes),
						fmt.Sprint(ge.Frees), fmt.Sprint(ge.FreeBytes))
				}
			}
		}
	}

	// Build freedMap and aliveMap site-attribution data (exported to independent sheets).
	freedMap := make(map[string]*siteInfo)
	for _, gc := range gcs {
		for _, site := range gc.FreedSites {
			key := site.Func + "|" + site.Loc
			si, ok := freedMap[key]
			if !ok { si = &siteInfo{Func: site.Func, Loc: site.Loc, Refs: make(map[string]bool)}; freedMap[key] = si }
			si.TotalObjs += site.Objs; si.TotalBytes += site.Bytes; si.Refs[site.Refs] = true
		}
	}
	aliveMap := make(map[string]*siteInfo)
	for i := len(gcs) - 1; i >= 0; i-- {
		if len(gcs[i].AliveSites) > 0 {
			for _, site := range gcs[i].AliveSites {
				key := site.Func + "|" + site.Loc
				if _, ok := aliveMap[key]; !ok {
					aliveMap[key] = &siteInfo{Func: site.Func, Loc: site.Loc,
						TotalObjs: site.Objs, TotalBytes: site.Bytes, Refs: make(map[string]bool)}
				}
				aliveMap[key].Refs[site.Refs] = true
			}
			break
		}
	}
	// Compute file:line cross-reference data (exported to independent sheets).
	freedByLine := make(map[string]*lineAgg)
	aliveByLine := make(map[string]*lineAgg)
	for _, si := range freedMap {
		loc := firstFileLine(si.Func, si.Loc)
		if loc == "" { continue }
		a, ok := freedByLine[loc]
		if !ok { a = &lineAgg{Funcs: make(map[string]bool), Types: make(map[string]bool)}; freedByLine[loc] = a }
		a.FreedObjs += si.TotalObjs
		a.FreedBytes += si.TotalBytes
		a.Funcs[si.Func] = true
		for _, t := range extractTypes(si.Refs) { a.Types[t] = true }
	}
	for _, si := range aliveMap {
		loc := firstFileLine(si.Func, si.Loc)
		if loc == "" { continue }
		a, ok := aliveByLine[loc]
		if !ok { a = &lineAgg{Funcs: make(map[string]bool)}; aliveByLine[loc] = a }
		a.AliveObjs += si.TotalObjs
		a.AliveBytes += si.TotalBytes
		a.Funcs[si.Func] = true
	}
	var bothLines, onlyLines []string
	for loc := range freedByLine {
		if _, ok := aliveByLine[loc]; ok {
			bothLines = append(bothLines, loc)
		} else {
			onlyLines = append(onlyLines, loc)
		}
	}
	sort.Slice(bothLines, func(i, j int) bool {
		return freedByLine[bothLines[i]].FreedBytes > freedByLine[bothLines[j]].FreedBytes
	})
	sort.Slice(onlyLines, func(i, j int) bool {
		return freedByLine[onlyLines[i]].FreedBytes > freedByLine[onlyLines[j]].FreedBytes
	})

	// ═══════════════════════════════════════════════════════════════
	// Session Lifecycle Analysis
	// ═══════════════════════════════════════════════════════════════
	if agg != nil {
		s.addBlank()
		s.addRow(fmt.Sprintf("=== Session Lifecycle Analysis (%d lifecycle sessions detected) ===", agg.SessionCount))

		// Compact session ID listing.
		shown := agg.Sessions
		if len(shown) > 10 {
			shown = shown[:10]
		}
		sidStrs := make([]string, len(shown))
		for i, sid := range shown {
			sidStrs[i] = fmt.Sprintf("#%d", sid)
		}
		sidSummary := strings.Join(sidStrs, ", ")
		if len(agg.Sessions) > 10 {
			sidSummary += fmt.Sprintf(", ... (+%d more)", len(agg.Sessions)-10)
		}
		s.addRow("Lifecycle Sessions:", sidSummary)
		s.addRow("Methodology: auto-detected sessions with a visible in-session phase and >=2 end-marked GCs.")
	s.addRow("  First end-marked GC = end-triggered GC (in-session snapshot); second = first post-session GC.")
		s.addBlank()

		// Aggregated lifecycle totals.
		shortTotal := 0
		shortTotalBytes := 0
		for _, si := range agg.ShortLived { shortTotal += si.TotalObjs; shortTotalBytes += si.TotalBytes }
		sessTotal := 0
		sessTotalBytes := 0
		for _, si := range agg.SessLifetime { sessTotal += si.TotalObjs; sessTotalBytes += si.TotalBytes }
		lateTotal := 0
		lateTotalBytes := 0
		for _, si := range agg.LateAlloc { lateTotal += si.TotalObjs; lateTotalBytes += si.TotalBytes }
		nfTotal := 0
		nfTotalBytes := 0
		for _, si := range agg.NotFreed { nfTotal += si.TotalObjs; nfTotalBytes += si.TotalBytes }

		s.addRow("=== Aggregated Lifecycle Summary ===")
		s.addRow("Short-lived (freed ≤ end-triggered GC)",
			fmt.Sprintf("%d objs, %d sites", shortTotal, len(agg.ShortLived)),
			fmt.Sprintf("%d bytes", shortTotalBytes))
		s.addRow("Session-lifetime (alive at end GC, freed after end)",
			fmt.Sprintf("%d objs, %d sites", sessTotal, len(agg.SessLifetime)),
			fmt.Sprintf("%d bytes", sessTotalBytes))
		s.addRow("Late-alloc (freed after end, not in end-GC alive set)",
			fmt.Sprintf("%d objs, %d sites", lateTotal, len(agg.LateAlloc)),
			fmt.Sprintf("%d bytes", lateTotalBytes))
		s.addRow("Runtime-persistent (still alive at final GC)",
			fmt.Sprintf("%d objs, %d sites", nfTotal, len(agg.NotFreed)),
			fmt.Sprintf("%d bytes", nfTotalBytes))
		s.addBlank()
		s.addRow("Aggregated total across lifecycle sessions",
			fmt.Sprintf("%d objs", shortTotal+sessTotal+lateTotal+nfTotal),
			fmt.Sprintf("%d bytes", shortTotalBytes+sessTotalBytes+lateTotalBytes+nfTotalBytes))
		s.addBlank()

		// Create separate sheets using buildSiteSheet.
		shortSheet := buildSiteSheet(data.Mode+" - 短周期对象", "=== 短周期对象 (Short-Lived Freed) ===", agg.ShortLived)
		sessSheet := buildSiteSheet(data.Mode+" - 会话周期对象", "=== 会话周期对象 (Session-Lifetime Freed) ===", agg.SessLifetime)
		lateSheet := buildSiteSheet(data.Mode+" - Late-alloc Freed", "=== Late-alloc Freed ===", agg.LateAlloc)
		rpSheet := buildSiteSheet(data.Mode+" - Runtime-Persistent", "=== Runtime-Persistent (Never Freed) ===", agg.NotFreed)
		extraSheets = append(extraSheets, shortSheet, sessSheet, lateSheet, rpSheet)
	} else {
			// Non-lifecycle: freed-only → 短周期, both-freed → 会话周期, all alive → Runtime.
			shortOnly := make(map[string]*siteInfo)
			sessBoth := make(map[string]*siteInfo)
			for key, si := range freedMap {
				if _, ok := aliveMap[key]; ok {
					sessBoth[key] = si
				} else {
					shortOnly[key] = si
				}
			}
			extraSheets = append(extraSheets,
				buildSiteSheet(data.Mode+" - 短周期对象", "=== 短周期对象 (Freed Sites) ===", shortOnly),
				buildSiteSheet(data.Mode+" - 会话周期对象", "=== 会话周期对象 (Freed Sites) ===", sessBoth),
				buildSiteSheet(data.Mode+" - Runtime-Persistent", "=== Runtime-Persistent (Never Freed) ===", aliveMap))
	}
	if strings.Contains(strings.ToLower(data.Mode), "reprint") {
		s.addBlank()
		s.addRow("=== Session Timeline (Re-print Verification) ===")
		for _, sk := range sorted {
			sa := sids[sk]
			s.addBlank()
			s.addRow(fmt.Sprintf("Session %s (GID=%d)", sessionDisplay(sk), sa.GID))
			s.addHeaderRow("GC", "Type", "Allocs", "Frees", "Alive", "end?")
			var appGCs []int
			for _, gc := range gcs {
				for _, se := range gc.Sessions {
					if sessionKey(se.ID, se.Generation) != sk {
						continue
					}
					typ := "first print"
					if se.End != "" { typ = "re-print" }
					hasEnd := "NO"
					if se.End != "" { hasEnd = "YES" }
					s.addRow(fmt.Sprint(gc.GC), typ, fmt.Sprint(se.Allocs), fmt.Sprint(se.Frees), fmt.Sprint(se.Alive), hasEnd)
					appGCs = append(appGCs, gc.GC)
				}
			}
			if len(appGCs) >= 2 {
				for mid := appGCs[0] + 1; mid < appGCs[len(appGCs)-1]; mid++ {
					skipped := true
					for _, agc := range appGCs { if agc == mid { skipped = false; break } }
					if skipped {
						s.addRow(fmt.Sprint(mid), "(skipped)", "", "", "", "")
					}
				}
			}
		}
	}

	// Always create independent sheets for Freed/Alive/Both/Only sections.
	extraSheets = append(extraSheets,
		buildSiteSheet(data.Mode+" - Freed Sites", "=== Freed Sites ===", freedMap),
		buildSiteSheet(data.Mode+" - Alive Sites", "=== Alive Sites ===", aliveMap),
		buildLineXRefBothSheet(data.Mode+" - Both Freed & Alive", freedByLine, aliveByLine, bothLines),
		buildLineXRefOnlySheet(data.Mode+" - Only in Freed", freedByLine, onlyLines))

	return append([]*xlsxSheet{s}, extraSheets...)
}

// lineAgg aggregates freed/alive data per file:line for cross-reference sheets.
type lineAgg struct {
	FreedObjs, FreedBytes, AliveObjs, AliveBytes int
	Funcs                                        map[string]bool
	Types                                        map[string]bool
}

// buildLineXRefBothSheet creates the "Both Freed & Alive" cross-reference sheet.
func buildLineXRefBothSheet(name string, freedByLine, aliveByLine map[string]*lineAgg, bothLines []string) *xlsxSheet {
	s := &xlsxSheet{name: name, colWidths: make([]float64, 20)}
	s.addRow("=== Alloc File:Line in Both Freed & Alive ===")
	s.addHeaderRow("Alloc File:Line", "Freed Objs", "Freed Bytes", "Alive Objs", "Alive Bytes", "#Stacks", "Call Stacks")
	if len(bothLines) == 0 {
		s.addRow("(none)")
	} else {
		for _, loc := range bothLines {
			fa := freedByLine[loc]
			aa := aliveByLine[loc]
			funcs := make([]string, 0, len(fa.Funcs))
			for f := range fa.Funcs { funcs = append(funcs, f) }
			for f := range aa.Funcs { funcs = append(funcs, f) }
			sort.Strings(funcs)
			fnStr := strings.Join(funcs, "; ")
			if len(fnStr) > 10000 { fnStr = fnStr[:9997] + "..." }
			s.addRow(loc, fmt.Sprint(fa.FreedObjs), fmt.Sprint(fa.FreedBytes),
				fmt.Sprint(aa.AliveObjs), fmt.Sprint(aa.AliveBytes),
				fmt.Sprint(len(funcs)), fnStr)
		}
	}
	return s
}

// buildLineXRefOnlySheet creates the "Only in Freed" cross-reference sheet.
func buildLineXRefOnlySheet(name string, freedByLine map[string]*lineAgg, onlyLines []string) *xlsxSheet {
	s := &xlsxSheet{name: name, colWidths: make([]float64, 20)}
	s.addRow("=== Alloc File:Line Only in Freed (fully dead) ===")
	s.addHeaderRow("Alloc File:Line", "Type", "Freed Objs", "Freed Bytes", "#Stacks", "Call Stacks")
	if len(onlyLines) == 0 {
		s.addRow("(none)")
	} else {
		for _, loc := range onlyLines {
			fa := freedByLine[loc]
			types := make([]string, 0, len(fa.Types))
			for t := range fa.Types { types = append(types, t) }
			sort.Strings(types)
			typeStr := strings.Join(types, "; ")
			funcs := make([]string, 0, len(fa.Funcs))
			for f := range fa.Funcs { funcs = append(funcs, f) }
			sort.Strings(funcs)
			fnStr := strings.Join(funcs, "; ")
			if len(fnStr) > 10000 { fnStr = fnStr[:9997] + "..." }
			s.addRow(loc, typeStr, fmt.Sprint(fa.FreedObjs), fmt.Sprint(fa.FreedBytes),
				fmt.Sprint(len(funcs)), fnStr)
		}
	}
	return s
}

func checkMatch(a, b int) string {
	if a == b {
		return "✓"
	}
	return fmt.Sprintf("✗ diff=%d", a-b)
}

func shortLoc(loc string) string {
	if idx := strings.Index(loc, ":"); idx >= 0 {
		base := filepath.Base(loc[:idx])
		return base + loc[idx:]
	}
	return loc
}

// firstFileLine extracts the first (file:line) from a call stack string.
// The call stack format from gcdeadtrace is:
//
//	topFunc (file1.go:123) < caller (file2.go:456) < ...
//
// Returns fallback when the stack doesn't contain a (file:line) pair.
func firstFileLine(stack, fallback string) string {
	idx := strings.Index(stack, " (")
	if idx < 0 {
		return fallback
	}
	start := idx + 2
	end := strings.Index(stack[start:], ")")
	if end < 0 {
		return fallback
	}
	return stack[start : start+end]
}

// extractTypes extracts unique @type annotations from a map of ref strings.
// Refs can contain multiple [session ...] blocks, e.g.:
//
//	"[session #3001: 1 objs, 256 bytes @uint8 (gid=18)] [session #3001: 1 objs, 256 bytes @uint8 (gid=19)]"
//
// Each block may also omit the type entirely, e.g. "[session #4002: 1 objs, 32 bytes (gid=6)]".
func extractTypes(refs map[string]bool) []string {
	seen := make(map[string]bool)
	for r := range refs {
		parts := strings.Split(r, "] [")
		for _, part := range parts {
			atIdx := strings.Index(part, "@")
			if atIdx < 0 {
				continue
			}
			rest := part[atIdx+1:]
			end := strings.IndexAny(rest, " ]")
			if end < 0 {
				end = len(rest)
			}
			t := rest[:end]
			if t != "" {
				seen[t] = true
			}
		}
	}
	var types []string
	for t := range seen { types = append(types, t) }
	sort.Strings(types)
	return types
}

// ── main ───────────────────────────────────────────────────────────

func main() {
	var inputFiles []string
	if len(os.Args) > 1 {
		inputFiles = os.Args[1:]
	} else {
		for _, dir := range []string{".", "output"} {
			for _, ext := range []string{"gcdeadtrace_*.txt", "gcdeadtrace_*.log", "*_stderr.log"} {
				pattern := filepath.Join(dir, ext)
				matches, err := filepath.Glob(pattern)
				if err == nil {
					inputFiles = append(inputFiles, matches...)
				}
			}
		}
		inputFiles = unique(inputFiles)
		if len(inputFiles) == 0 {
			fmt.Println("  No gcdeadtrace_*.txt / gcdeadtrace_*.log files found in ./ or output/")
			os.Exit(1)
		}
	}

	var allData []*ParsedData
	for _, inPath := range inputFiles {
		if _, err := os.Stat(inPath); os.IsNotExist(err) {
			fmt.Printf("  [SKIP] file not found: %s\n", inPath)
			continue
		}
		label := strings.TrimSuffix(filepath.Base(inPath), ".log")
		label = strings.TrimSuffix(label, ".txt")
		fmt.Printf("  Parsing %s ... ", label)
		data := parseFile(inPath)
		allData = append(allData, data)
		if len(data.GCCycles) > 0 {
			maxSess := 0
			for _, gc := range data.GCCycles {
				if len(gc.Sessions) > maxSess { maxSess = len(gc.Sessions) }
			}
			runNote := ""
			if len(data.RunStart) > 0 { runNote = fmt.Sprintf(", %d runs (GC reset detected)", len(data.RunStart)+1) }
			fmt.Printf("%d GC cycles%s, up to %d sessions/cycle\n", len(data.GCCycles), runNote, maxSess)
		} else {
			fmt.Println("0 GC cycles")
		}
	}

	if len(allData) == 0 {
		fmt.Println("  No data to process.")
		os.Exit(1)
	}

	builder := xlsxBuilder{}
	builder.sheets = append(builder.sheets, *buildOverviewSheet(allData))
	for _, d := range allData {
		for _, s := range buildModeSheet(d) {
			builder.sheets = append(builder.sheets, *s)
		}
	}

	outPath := "gcdeadtrace_report_lifecycle.xlsx"
	fmt.Printf("\n  Writing %s ... ", outPath)
	if err := builder.writeXLSX(outPath); err != nil {
		fmt.Printf("ERROR: %v\n", err)
		os.Exit(1)
	}
	info, _ := os.Stat(outPath)
	fmt.Printf("done (%d bytes)\n", info.Size())
	fmt.Printf("\n  %d file(s) → %d sheet(s)\n", len(inputFiles), len(builder.sheets))
	fmt.Println("  Open gcdeadtrace_report_lifecycle.xlsx in Excel.")
}

// unique deduplicates a string slice while preserving order.
func unique(s []string) []string {
	seen := make(map[string]bool, len(s))
	r := make([]string, 0, len(s))
	for _, v := range s {
		if seen[v] {
			continue
		}
		seen[v] = true
		r = append(r, v)
	}
	return r
}
