// excel_report — gcdeadtrace demo XLSX report generator.
//
// Reads gcdeadtrace stderr output files, parses per-GC-cycle session data,
// and generates a multi-sheet Excel file with Overview, per-mode detail
// tables, session timelines, and allocation site attribution.
//
// Usage:
//   excel_report.exe [file1.txt file2.txt ...]
//
//   If no arguments are given, scans the current directory and output/
//   subdirectory for gcdeadtrace_*.txt / gcdeadtrace_*.log files automatically.
//   Otherwise, processes the specified files in the given order.
//   Each file becomes one sheet (named by its filename without .txt prefix).
//
// Output:
//   output/gcdeadtrace_report.xlsx — multi-sheet Excel workbook
//
// Build:
//   go build -o excel_report.exe excel_report.go
//
// Prerequisites:
//   - Go toolchain (>= 1.21)
//   - Input files generated by demo.exe with GODEBUG=gcdeadtrace=1
//   - No external Go dependencies (uses only archive/zip + encoding/xml)
package main

import (
	"archive/zip"
	"bufio"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// ── data types ─────────────────────────────────────────────────────

type SessionEntry struct {
	ID, GID                         int
	Allocs, AllocBytes              int
	Frees, FreeBytes                int
	Alive, AliveBytes               int
	Start, End                      string
}

type FreedAlive struct {
	Objs, Bytes, Sites int
}

type SiteLine struct {
	Func, Loc string
	Objs, Bytes int
	Refs       string
}

type GCBlock struct {
	GC                          int
	Sessions                    []SessionEntry
	Freed                       *FreedAlive
	Alive                       *FreedAlive
	FreedSites, AliveSites      []SiteLine
}

type ParsedData struct {
	Mode    string
	GCCycles []GCBlock
}

// ── parsing ────────────────────────────────────────────────────────

var (
	sessionRe = regexp.MustCompile(
		`\s*session #(\d+) \(gid=(\d+)\): (\d+) allocs \((\d+) bytes\), (\d+) freed \((\d+) bytes\), (\d+) alive \((\d+) bytes\)` +
			`\s*(?:\[start: ([^]]+?)(?:, end: ([^]]+?))?\])?\s*`,
	)
	freedSumRe = regexp.MustCompile(`gcdeadsession:freed:\s*(\d+) session objs \((\d+) bytes\) freed from (\d+) sites`)
	aliveSumRe = regexp.MustCompile(`gcdeadsession:alive:\s*(\d+) session objs \((\d+) bytes\) still alive from (\d+) sites`)
	gcHeaderRe = regexp.MustCompile(`=== GC #(\d+) ===`)
	siteLineRe = regexp.MustCompile(`\s+(.+) \((\S+:\d+)\).*:\s*(\d+) session objs, (\d+) session bytes\s+(.*)`)
)

func parseInt(s string) int {
	n, _ := strconv.Atoi(s)
	return n
}

func parseFile(path string) *ParsedData {
	f, _ := os.Open(path)
	defer f.Close()
	base := strings.TrimSuffix(filepath.Base(path), ".log")
	base = strings.TrimSuffix(base, ".txt")
	mode := strings.TrimPrefix(base, "gcdeadtrace_demo_")
	data := &ParsedData{Mode: mode}
	scanner := bufio.NewScanner(f)
	var lines []string
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}
	i := 0
	for i < len(lines) && !gcHeaderRe.MatchString(lines[i]) {
		i++
	}
	for i < len(lines) {
		m := gcHeaderRe.FindStringSubmatch(lines[i])
		if m == nil { i++; continue }
		gcNum := parseInt(m[1])
		i++
		block := GCBlock{GC: gcNum}
		for i < len(lines) && !gcHeaderRe.MatchString(lines[i]) {
			line := lines[i]
			if sm := sessionRe.FindStringSubmatch(line); sm != nil {
				block.Sessions = append(block.Sessions, SessionEntry{
					ID: parseInt(sm[1]), GID: parseInt(sm[2]),
					Allocs: parseInt(sm[3]), AllocBytes: parseInt(sm[4]),
					Frees: parseInt(sm[5]), FreeBytes: parseInt(sm[6]),
					Alive: parseInt(sm[7]), AliveBytes: parseInt(sm[8]),
					Start: sm[9], End: sm[10],
				})
				i++; continue
			}
			if fm := freedSumRe.FindStringSubmatch(line); fm != nil {
				block.Freed = &FreedAlive{Objs: parseInt(fm[1]), Bytes: parseInt(fm[2]), Sites: parseInt(fm[3])}
				i++
				for i < len(lines) {
					sl := siteLineRe.FindStringSubmatch(lines[i])
					if sl == nil { break }
					block.FreedSites = append(block.FreedSites, SiteLine{strings.TrimSpace(sl[1]), sl[2], parseInt(sl[3]), parseInt(sl[4]), strings.TrimSpace(sl[5])})
					i++
				}
				continue
			}
			if am := aliveSumRe.FindStringSubmatch(line); am != nil {
				block.Alive = &FreedAlive{Objs: parseInt(am[1]), Bytes: parseInt(am[2]), Sites: parseInt(am[3])}
				i++
				for i < len(lines) {
					sl := siteLineRe.FindStringSubmatch(lines[i])
					if sl == nil { break }
					block.AliveSites = append(block.AliveSites, SiteLine{strings.TrimSpace(sl[1]), sl[2], parseInt(sl[3]), parseInt(sl[4]), strings.TrimSpace(sl[5])})
					i++
				}
				continue
			}
			i++
		}
		data.GCCycles = append(data.GCCycles, block)
	}
	return data
}

// ── XLSX builder ──────────────────────────────────────────────────

type xlsxSheet struct {
	name      string
	rows      [][]string
	colWidths []float64
}

const maxColWidth = 70.0

func (s *xlsxSheet) addRow(cells ...string) {
	s.rows = append(s.rows, cells)
	for i, c := range cells {
		w := float64(len(c)) * 1.05
		if w < 10 { w = 10 }
		if w > maxColWidth { w = maxColWidth }
		if w > s.colWidths[i] { s.colWidths[i] = w }
	}
}

func (s *xlsxSheet) addBlank() {
	s.rows = append(s.rows, nil)
}

func (s *xlsxSheet) addHeaderRow(cells ...string) {
	s.rows = append(s.rows, cells)
}

func escXML(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, "\"", "&quot;")
	return s
}

func colLetter(i int) string {
	return string(rune('A' + i))
}

func fmtFloat(f float64) string {
	if f == math.Trunc(f) {
		return fmt.Sprintf("%.0f", f)
	}
	return fmt.Sprintf("%.1f", f)
}

func (xb *xlsxBuilder) writeXLSX(path string) error {
	f, err := os.Create(path)
	if err != nil { return err }
	defer f.Close()

	w := zip.NewWriter(f)
	defer w.Close()

	// [Content_Types].xml
	ct := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
  <Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/>`
	for i := range xb.sheets {
		ct += fmt.Sprintf("\n  <Override PartName=\"/xl/worksheets/sheet%d.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>", i+1)
	}
	ct += "\n</Types>"
	xb.writeFile(w, "[Content_Types].xml", ct)

	// _rels/.rels
	rels := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>`
	xb.writeFile(w, "_rels/.rels", rels)

	// xl/workbook.xml
	wb := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
          xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>`
	for i, s := range xb.sheets {
		wb += fmt.Sprintf("\n    <sheet name=\"%s\" sheetId=\"%d\" r:id=\"rId%d\"/>", escXML(s.name), i+1, i+3)
	}
	wb += "\n  </sheets>\n</workbook>"
	xb.writeFile(w, "xl/workbook.xml", wb)

	// xl/_rels/workbook.xml.rels
	wbRels := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>`
	for i := range xb.sheets {
		wbRels += fmt.Sprintf("\n  <Relationship Id=\"rId%d\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet%d.xml\"/>", i+3, i+1)
	}
	wbRels += "\n</Relationships>"
	xb.writeFile(w, "xl/_rels/workbook.xml.rels", wbRels)

	// xl/styles.xml — bold header font
	styles := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <fonts count="2">
    <font><sz val="11"/><name val="Consolas"/></font>
    <font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Consolas"/></font>
  </fonts>
  <fills count="3">
    <fill><patternFill patternType="none"/></fill>
    <fill><patternFill patternType="gray125"/></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FF4472C4"/></patternFill></fill>
  </fills>
  <borders count="2">
    <border><left/><right/><top/><bottom/><diagonal/></border>
    <border>
      <left style="thin"><color auto="1"/></left>
      <right style="thin"><color auto="1"/></right>
      <top style="thin"><color auto="1"/></top>
      <bottom style="thin"><color auto="1"/></bottom>
      <diagonal/>
    </border>
  </borders>
  <cellStyleXfs count="1">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0"/>
  </cellStyleXfs>
  <cellXfs count="4">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
    <xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1" applyAlignment="1"><alignment horizontal="center"/></xf>
    <xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1"/>
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0" applyFont="1"><font><b/><sz val="12"/><name val="Consolas"/></font></xf>
  </cellXfs>
</styleSheet>`
	xb.writeFile(w, "xl/styles.xml", styles)

	// xl/sharedStrings.xml
	ss := `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="0" uniqueCount="0"></sst>`
	xb.writeFile(w, "xl/sharedStrings.xml", ss)

	// xl/worksheets/sheetN.xml
	for si, sheet := range xb.sheets {
		colXml := "<cols>"
		for i, w := range sheet.colWidths {
			if w > 0 {
				colXml += fmt.Sprintf("<col min=\"%d\" max=\"%d\" width=\"%.1f\" customWidth=\"1\"/>", i+1, i+1, w)
			}
		}
		colXml += "</cols>"

		rowsXml := ""
		inSection := false
		for ri, row := range sheet.rows {
			if row == nil {
				rowsXml += fmt.Sprintf("<row r=\"%d\"></row>", ri+1)
				inSection = false
				continue
			}
			// Determine style: header row (first or after blank) → style 1 (blue bold)
			// Section title (starts with "===" or "Mode:") → style 3 (bold 12pt)
			// Normal data → style 2 (border only)
			// Others → style 0
			styleIdx := 0
			if !inSection {
				styleIdx = 1 // blue bold header
			} else {
				styleIdx = 2 // bordered data
			}
			if len(row) > 0 && (strings.HasPrefix(row[0], "==") || row[0] == "Mode:" || strings.HasPrefix(row[0], "Session #")) {
				styleIdx = 3 // section title
			}
			inSection = true

			rowsXml += fmt.Sprintf("<row r=\"%d\">", ri+1)
			for ci, cell := range row {
				ref := fmt.Sprintf("%s%d", colLetter(ci), ri+1)
				if cell == "" {
					rowsXml += fmt.Sprintf("<c r=\"%s\" s=\"%d\"/>", ref, styleIdx)
					continue
				}
				if n, err := strconv.Atoi(cell); err == nil {
					rowsXml += fmt.Sprintf("<c r=\"%s\" s=\"%d\"><v>%d</v></c>", ref, styleIdx, n)
				} else if f, err := strconv.ParseFloat(cell, 64); err == nil {
					rowsXml += fmt.Sprintf("<c r=\"%s\" s=\"%d\"><v>%s</v></c>", ref, styleIdx, fmtFloat(f))
				} else {
					rowsXml += fmt.Sprintf("<c r=\"%s\" t=\"inlineStr\" s=\"%d\"><is><t>%s</t></is></c>", ref, styleIdx, escXML(cell))
				}
			}
			rowsXml += "</row>"
		}

		sheetXml := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
           xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  %s
  <sheetData>%s</sheetData>
</worksheet>`, colXml, rowsXml)

		xb.writeFile(w, fmt.Sprintf("xl/worksheets/sheet%d.xml", si+1), sheetXml)
	}

	return nil
}

type xlsxBuilder struct {
	sheets []xlsxSheet
}

func (xb *xlsxBuilder) writeFile(w *zip.Writer, name, content string) {
	f, _ := w.Create(name)
	f.Write([]byte(content))
}

// ── build sheets from parsed data ─────────────────────────────────

type sessAgg struct {
	GID, FirstGC, LastGC      int
	Start, End                string
	CumAllocs, CumFrees       int
	MaxAlive, MaxAliveBytes   int
}

func buildOverviewSheet(allData []*ParsedData) *xlsxSheet {
	s := &xlsxSheet{name: "Overview", colWidths: make([]float64, 20)}
	s.addHeaderRow("Mode", "GC Cycles", "Sessions", "Freed Objs", "Alive Objs", "Avg Freed/GC", "Avg Alive/GC")
	for _, d := range allData {
		tf, ta := 0, 0
		for _, gc := range d.GCCycles {
			if gc.Freed != nil { tf += gc.Freed.Objs }
			if gc.Alive != nil { ta += gc.Alive.Objs }
		}
		sessSet := make(map[int]bool)
		for _, gc := range d.GCCycles {
			for _, se := range gc.Sessions { sessSet[se.ID] = true }
		}
		gcN := len(d.GCCycles)
		s.addRow(d.Mode, fmt.Sprint(gcN), fmt.Sprint(len(sessSet)),
			fmt.Sprint(tf), fmt.Sprint(ta),
			fmt.Sprintf("%.1f", float64(tf)/float64(gcN)),
			fmt.Sprintf("%.1f", float64(ta)/float64(gcN)))
	}
	return s
}

func buildModeSheet(data *ParsedData) *xlsxSheet {
	s := &xlsxSheet{name: data.Mode, colWidths: make([]float64, 20)}
	gcs := data.GCCycles

	tf, ta := 0, 0
	for _, gc := range gcs {
		if gc.Freed != nil { tf += gc.Freed.Objs }
		if gc.Alive != nil { ta += gc.Alive.Objs }
	}
	sessSet := make(map[int]bool)
	for _, gc := range gcs {
		for _, se := range gc.Sessions { sessSet[se.ID] = true }
	}

	s.addRow("Mode:", data.Mode)
	s.addRow("GC Cycles:", fmt.Sprint(len(gcs)))
	s.addRow("Sessions:", fmt.Sprint(len(sessSet)))
	s.addRow("Total Freed:", fmt.Sprint(tf))
	s.addRow("Total Alive:", fmt.Sprint(ta))
	s.addBlank()

	// Per-GC Summary
	s.addHeaderRow("GC", "Sessions", "Freed Objs", "Freed Bytes", "Alive Objs", "Alive Bytes")
	for _, gc := range gcs {
		fO, fB, aO, aB := "0", "0", "0", "0"
		if gc.Freed != nil { fO = fmt.Sprint(gc.Freed.Objs); fB = fmt.Sprint(gc.Freed.Bytes) }
		if gc.Alive != nil { aO = fmt.Sprint(gc.Alive.Objs); aB = fmt.Sprint(gc.Alive.Bytes) }
		s.addRow(fmt.Sprint(gc.GC), fmt.Sprint(len(gc.Sessions)), fO, fB, aO, aB)
	}
	s.addBlank()

	// Session Detail
	s.addHeaderRow("Session", "GID", "First GC", "Last GC", "Start", "End", "Total Allocs", "Total Frees", "Max Alive")
	sids := make(map[int]*sessAgg)
	for _, gc := range gcs {
		for _, se := range gc.Sessions {
			sa, ok := sids[se.ID]
			if !ok {
				sa = &sessAgg{GID: se.GID, FirstGC: gc.GC, Start: se.Start}
				sids[se.ID] = sa
			}
			sa.LastGC = gc.GC
			sa.CumAllocs += se.Allocs
			sa.CumFrees += se.Frees
			if se.Alive > sa.MaxAlive { sa.MaxAlive = se.Alive; sa.MaxAliveBytes = se.AliveBytes }
			if se.End != "" { sa.End = se.End }
		}
	}
	var sorted []int
	for id := range sids { sorted = append(sorted, id) }
	sort.Ints(sorted)
	for _, id := range sorted {
		sa := sids[id]
		s.addRow(fmt.Sprintf("#%d", id), fmt.Sprint(sa.GID),
			fmt.Sprintf("GC#%d", sa.FirstGC), fmt.Sprintf("GC#%d", sa.LastGC),
			shortLoc(sa.Start), shortLoc(sa.End),
			fmt.Sprint(sa.CumAllocs), fmt.Sprint(sa.CumFrees), fmt.Sprint(sa.MaxAlive))
	}

	// Freed Site Attribution
	s.addBlank()
	s.addRow("=== Freed Sites ===")
	s.addHeaderRow("Allocation Site", "Alloc File:Line", "Freed Objs", "Freed Bytes", "Session Refs")
	type siteInfo struct {
		Func, Loc          string
		TotalObjs, TotalBytes int
		Refs               map[string]bool
	}
	emitSites := func(siteMap map[string]*siteInfo, title string) {
		var sites []*siteInfo
		for _, si := range siteMap { sites = append(sites, si) }
		sort.Slice(sites, func(i, j int) bool { return sites[i].TotalObjs > sites[j].TotalObjs })
		for _, si := range sites {
			var refs []string
			for r := range si.Refs { refs = append(refs, r) }
			sort.Strings(refs)
			refStr := strings.Join(refs, "; ")
			if len(refStr) > 1000 { refStr = refStr[:997] + "..." }
			// Extract the first (file:line) from the call stack = actual alloc point.
			// For simple stacks (no call chain), fall back to si.Loc.
			loc := firstFileLine(si.Func, si.Loc)
			s.addRow(si.Func, loc, fmt.Sprint(si.TotalObjs), fmt.Sprint(si.TotalBytes), refStr)
		}
	}
	freedMap := make(map[string]*siteInfo)
	for _, gc := range gcs {
		for _, site := range gc.FreedSites {
			key := site.Func + "|" + site.Loc
			si, ok := freedMap[key]
			if !ok { si = &siteInfo{Func: site.Func, Loc: site.Loc, Refs: make(map[string]bool)}; freedMap[key] = si }
			si.TotalObjs += site.Objs; si.TotalBytes += site.Bytes; si.Refs[site.Refs] = true
		}
	}
	emitSites(freedMap, "Freed")

	// Alive Site Attribution
	s.addBlank()
	s.addRow("=== Alive Sites ===")
	s.addHeaderRow("Allocation Site", "Alloc File:Line", "Alive Objs", "Alive Bytes", "Session Refs")
	aliveMap := make(map[string]*siteInfo)
	for _, gc := range gcs {
		for _, site := range gc.AliveSites {
			key := site.Func + "|" + site.Loc
			si, ok := aliveMap[key]
			if !ok { si = &siteInfo{Func: site.Func, Loc: site.Loc, Refs: make(map[string]bool)}; aliveMap[key] = si }
			si.TotalObjs += site.Objs; si.TotalBytes += site.Bytes; si.Refs[site.Refs] = true
		}
	}
	emitSites(aliveMap, "Alive")

	// Cross-reference by Alloc File:Line
	s.addBlank()
	s.addRow("=== Alloc File:Line in Both Freed & Alive ===")
	s.addHeaderRow("Alloc File:Line", "Freed Objs", "Freed Bytes", "Alive Objs", "Alive Bytes", "Functions")
	type lineAgg struct {
		FreedObjs, FreedBytes, AliveObjs, AliveBytes int
		Funcs                                        map[string]bool
	}
	freedByLine := make(map[string]*lineAgg)
	aliveByLine := make(map[string]*lineAgg)
	for _, si := range freedMap {
		loc := firstFileLine(si.Func, si.Loc)
		if loc == "" { continue }
		a, ok := freedByLine[loc]
		if !ok { a = &lineAgg{Funcs: make(map[string]bool)}; freedByLine[loc] = a }
		a.FreedObjs += si.TotalObjs
		a.FreedBytes += si.TotalBytes
		a.Funcs[si.Func] = true
	}
	for _, si := range aliveMap {
		loc := firstFileLine(si.Func, si.Loc)
		if loc == "" { continue }
		a, ok := aliveByLine[loc]
		if !ok { a = &lineAgg{Funcs: make(map[string]bool)}; aliveByLine[loc] = a }
		a.AliveObjs += si.TotalObjs
		a.AliveBytes += si.TotalBytes
		a.Funcs[si.Func] = true
	}
	// Both freed & alive — sorted by Freed Bytes desc
	var bothLines []string
	for loc := range freedByLine {
		if _, ok := aliveByLine[loc]; ok {
			bothLines = append(bothLines, loc)
		}
	}
	sort.Slice(bothLines, func(i, j int) bool {
		return freedByLine[bothLines[i]].FreedBytes > freedByLine[bothLines[j]].FreedBytes
	})
	for _, loc := range bothLines {
		fa := freedByLine[loc]
		aa := aliveByLine[loc]
		funcs := make([]string, 0, len(fa.Funcs))
		for f := range fa.Funcs { funcs = append(funcs, f) }
		for f := range aa.Funcs { funcs = append(funcs, f) }
		sort.Strings(funcs)
		fnStr := strings.Join(funcs, "; ")
		if len(fnStr) > 200 { fnStr = fnStr[:197] + "..." }
		s.addRow(loc, fmt.Sprint(fa.FreedObjs), fmt.Sprint(fa.FreedBytes),
			fmt.Sprint(aa.AliveObjs), fmt.Sprint(aa.AliveBytes), fnStr)
	}
	if len(bothLines) == 0 {
		s.addRow("(none)")
	}

	// Freed only — sorted by Freed Bytes desc
	s.addBlank()
	s.addRow("=== Alloc File:Line Only in Freed (fully dead) ===")
	s.addHeaderRow("Alloc File:Line", "Freed Objs", "Freed Bytes", "Functions")
	var onlyLines []string
	for loc := range freedByLine {
		if _, ok := aliveByLine[loc]; !ok {
			onlyLines = append(onlyLines, loc)
		}
	}
	sort.Slice(onlyLines, func(i, j int) bool {
		return freedByLine[onlyLines[i]].FreedBytes > freedByLine[onlyLines[j]].FreedBytes
	})
	for _, loc := range onlyLines {
		fa := freedByLine[loc]
		funcs := make([]string, 0, len(fa.Funcs))
		for f := range fa.Funcs { funcs = append(funcs, f) }
		sort.Strings(funcs)
		fnStr := strings.Join(funcs, "; ")
		if len(fnStr) > 200 { fnStr = fnStr[:197] + "..." }
		s.addRow(loc, fmt.Sprint(fa.FreedObjs), fmt.Sprint(fa.FreedBytes), fnStr)
	}
	if len(onlyLines) == 0 {
		s.addRow("(none)")
	}

	// Reprint timeline
	if strings.Contains(strings.ToLower(data.Mode), "reprint") {
		s.addBlank()
		s.addRow("=== Session Timeline (Re-print Verification) ===")
		for _, id := range sorted {
			sa := sids[id]
			s.addBlank()
			s.addRow(fmt.Sprintf("Session #%d (GID=%d)", id, sa.GID))
			s.addHeaderRow("GC", "Type", "Allocs", "Frees", "Alive", "end?")
			var appGCs []int
			for _, gc := range gcs {
				for _, se := range gc.Sessions {
					if se.ID == id {
						typ := "first print"
						if se.End != "" { typ = "re-print" }
						hasEnd := "NO"
						if se.End != "" { hasEnd = "YES" }
						s.addRow(fmt.Sprint(gc.GC), typ, fmt.Sprint(se.Allocs), fmt.Sprint(se.Frees), fmt.Sprint(se.Alive), hasEnd)
						appGCs = append(appGCs, gc.GC)
					}
				}
			}
			if len(appGCs) >= 2 {
				for mid := appGCs[0] + 1; mid < appGCs[len(appGCs)-1]; mid++ {
					skipped := true
					for _, agc := range appGCs { if agc == mid { skipped = false; break } }
					if skipped {
						s.addRow(fmt.Sprint(mid), "(skipped)", "", "", "", "")
					}
				}
			}
		}
	}

	return s
}

func shortLoc(loc string) string {
	if idx := strings.Index(loc, ":"); idx >= 0 {
		base := filepath.Base(loc[:idx])
		return base + loc[idx:]
	}
	return loc
}

// firstFileLine extracts the first (file:line) from a call stack string.
// The call stack format from gcdeadtrace is:
//
//	topFunc (file1.go:123) < caller (file2.go:456) < ...
//
// Returns fallback when the stack doesn't contain a (file:line) pair.
func firstFileLine(stack, fallback string) string {
	idx := strings.Index(stack, " (")
	if idx < 0 {
		return fallback
	}
	start := idx + 2
	end := strings.Index(stack[start:], ")")
	if end < 0 {
		return fallback
	}
	return stack[start : start+end]
}

// ── main ───────────────────────────────────────────────────────────

func main() {
	// Collect input files: args, or auto-scan
	var inputFiles []string
	if len(os.Args) > 1 {
		inputFiles = os.Args[1:]
	} else {
		// Scan current dir + output/ subdir for gcdeadtrace_*.txt / *.log
		for _, dir := range []string{".", "output"} {
			for _, ext := range []string{"gcdeadtrace_*.txt", "gcdeadtrace_*.log"} {
				pattern := filepath.Join(dir, ext)
				matches, err := filepath.Glob(pattern)
				if err == nil {
					inputFiles = append(inputFiles, matches...)
				}
			}
		}
		inputFiles = unique(inputFiles)
		if len(inputFiles) == 0 {
			fmt.Println("  No gcdeadtrace_*.txt / gcdeadtrace_*.log files found in ./ or output/")
			os.Exit(1)
		}
	}

	var allData []*ParsedData
	for _, inPath := range inputFiles {
		if _, err := os.Stat(inPath); os.IsNotExist(err) {
			fmt.Printf("  [SKIP] file not found: %s\n", inPath)
			continue
		}
		// Use filename (without .txt/.log extension) as sheet label
		label := strings.TrimSuffix(filepath.Base(inPath), ".log")
		label = strings.TrimSuffix(label, ".txt")
		fmt.Printf("  Parsing %s ... ", label)
		data := parseFile(inPath)
		allData = append(allData, data)
		if len(data.GCCycles) > 0 {
			sessCount := len(data.GCCycles[0].Sessions)
			fmt.Printf("%d GC cycles, up to %d sessions/cycle\n", len(data.GCCycles), sessCount)
		} else {
			fmt.Println("0 GC cycles")
		}
	}

	if len(allData) == 0 {
		fmt.Println("  No data to process.")
		os.Exit(1)
	}

	builder := xlsxBuilder{}
	builder.sheets = append(builder.sheets, *buildOverviewSheet(allData))
	for _, d := range allData {
		builder.sheets = append(builder.sheets, *buildModeSheet(d))
	}

	outPath := "gcdeadtrace_report.xlsx"
	fmt.Printf("\n  Writing %s ... ", outPath)
	if err := builder.writeXLSX(outPath); err != nil {
		fmt.Printf("ERROR: %v\n", err)
		os.Exit(1)
	}
	info, _ := os.Stat(outPath)
	fmt.Printf("done (%d bytes)\n", info.Size())
	fmt.Printf("\n  %d file(s) → %d sheet(s)\n", len(inputFiles), len(allData)+1)
	fmt.Println("  Open gcdeadtrace_report.xlsx in Excel.")
}

// unique deduplicates a string slice while preserving order.
func unique(s []string) []string {
	seen := make(map[string]bool, len(s))
	r := make([]string, 0, len(s))
	for _, v := range s {
		if seen[v] {
			continue
		}
		seen[v] = true
		r = append(r, v)
	}
	return r
}
